### ISSUE TITLE
Indicators re-animate when an icon is removed 

### ISSUE THREAD

**Issue by danirabbit** [elementary/wingpanel#106]
1. Disable bluetooth and notifications
2. Have nightlight running, then disabled it (not snooze, disable)
3. When the nightlight icon is animated out of the panel, notice that the bluetooth and notifications icons re-slash

It appears that when an icon is removed from the panel, all of the icons (maybe even the whole menubar?) are destroyed and recreated. This causes these icons to re-animate.

**Comment by cassidyjames** [comment]
Same with the new caps/numlock icons: https://github.com/elementary/wingpanel-indicator-keyboard/pull/81#issuecomment-733877956_

**Comment by andrewdbate** [comment]
I believe this is the same issue I have on elementary OS 6.1.

When notifications are disabled, toggling caps lock causes the bell notification icon to flash. See video (6 seconds):

https://user-images.githubusercontent.com/2998569/154187810-6194cbea-5976-43af-9449-c097defa6b28.mp4
