### ISSUE TITLE
 wingpanel takes time to start

### ISSUE THREAD

**Issue by EvertonCosmo** [elementary/wingpanel#110]
Often after login the wingpanel takes a long time to start

**Comment by donadigo** [comment]
This looks like it should be fixed when this is merged: https://github.com/elementary/wingpanel/pull/103.

**Comment by leonardo-lemos** [comment]
Hello, how much time does it takes to start? Which version of elementary OS are you running?

**Comment by EvertonCosmo** [comment]
currently used at 0.4.1 and took about 30 seconds.

**Comment by danrabbit** [comment]
Closing since #103 was merged

**Comment by tuxiano** [comment]
Wingpanel and plank take a long time to load. Interestingly after a reboot it loads quickly but if I log out and in again it takes between 15 to 60 seconds to load.

Specs: Ryzen 7 2700X, 16 GB RAM, NVM SSD.
