### ISSUE TITLE
Wifi icon

### ISSUE THREAD

**Issue by ssspacez** [elementary/wingpanel#111]
I've noticed that sometimes the wifi icon becomes gray, but the wifi is working, I mean... I'm browsing the web but it was gray... It's weird, it happens just sometimes I don't know exactly what causes this, I've managed to take a screenshot:

![wifi](https://user-images.githubusercontent.com/34775187/39900071-ce051fd4-5495-11e8-8e39-5a786a0a857a.png)

As you can see it's connected and the wifi is working but the wifi icon is "gray" as if it was offline.

**Comment by danrabbit** [comment]
This just means you have poor signal. It is the icon for `network-wireless-signal-weak` :)
