### ISSUE TITLE
Indicators and icons not appearing in WingPanel

### ISSUE THREAD

**Issue by r3k4** [elementary/wingpanel#119]
I'm having a issue with WingPanel. 
The Dropbox indicator isn't present at all.

I'm up to date on all packages, fresh install from ubuntu 18.04

**Comment by tintou** [comment]
Dropbox use a 6 years old unsupported Indicator API
Closed as won't fix.

**Comment by r3k4** [comment]
@tintou not only dropbox, but also other applications is also not appearing in wingpanel.. like skype, steam, telegram, etc.

**Comment by donadigo** [comment]
To be able to see them you need to install a special package which is a compatibility layer - "wingpanel-indicator-ayatana".

In terminal:
sudo apt install wingpanel-indicator-ayatana

**Comment by r3k4** [comment]
@donadigo 
I have installed "wingpanel-indicator-ayatana", but still not appearing in tray.. is there any additional configuration for this ?

**Comment by cassidyjames** [comment]
Duplicate of #96
