### ISSUE TITLE
Window opens/can slide below wingpanel

### ISSUE THREAD

**Issue by arshubham** [elementary/wingpanel#130]
Steps:
1. Start a session.
2. Log out.
3. Log back in.

Affects all applications and reproducible every time.

Screenshots:
- Un-maximized window
![screenshot from 2018-07-07 13-42-31](https://user-images.githubusercontent.com/14235191/42408759-7a4e39bc-81ee-11e8-93a5-24d1da6528ef.png)

- Maximized window
![screenshot from 2018-07-07 13-42-46](https://user-images.githubusercontent.com/14235191/42408761-82c09aea-81ee-11e8-86ba-f5eb53a0e0ce.png)
Note that the titlebar is shorter in height.

**Comment by janxkoci** [comment]
I have the same issue, but only sometimes, and I haven't found a trigger yet. After some reboots it's fine, but other times it's like this. I was thinking it appeared after I enter the desktop settings (wallpaper, dock, etc.) but the issue also appears after cold start, at least sometimes.

**Comment by albergh** [comment]
I have a quick fix when that happens, unmaximize all apps, I open Gnome system monitor, search wingpanel, click on End process (don't worry, it will restart itself) and maximize again. That should do the trick untill the next reboot

**Comment by peteruithoven** [comment]
I've been noticing this as well sometimes. 

I'm pretty sure it has something to do with this animation:
https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L76-L94
If I increase that timeout interval to `1000 / panel_height` it doesn't seem to happen anymore.
```
Timeout.add (1000 / panel_height, animation_step);
```

**Comment by sprite-1** [comment]
@peteruithoven will you add it to the official source code?

**Comment by peteruithoven** [comment]
No sorry, because it increases the length of the animation and it doesn't fix the underlying issue. 
I believe the issues is that it animates and while it's animating it reads the height and uses that to declare it's height to the window manager, sometimes though the animation is delayed giving wrong height readouts.

**Comment by janxkoci** [comment]
I'm a bit surprised that height of wingpanel isn't hardcoded. I'm generally against hardcoding values, but since wingpanel is not meant to be editable, is there any harm?

**Comment by peteruithoven** [comment]
@janxkoci I don't get where you pull that assumption from, it kinda is hardcoded: 
https://github.com/elementary/wingpanel/blob/master/src/Widgets/Panel.vala#L33

I've been adding some logs and when the animation is longer I noticed that suddenly the `panel_height` ([code](https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L97)) changes from `24` to `30`. Looks like for some people this happens after the animation is complete and then the truts? are not updated.
So the question is, why the delayed height change from 24 to 30?

**Comment by janxkoci** [comment]
> ... I don't get where you pull that assumption from, it kinda is hardcoded:

From your previous comment:

> ... while it's animating it reads the height and uses that to declare it's height to the window manager...

I don't speak vala, sorry, I just really dislike this bug and so I'm trying to help, perhaps not in the smartest way possible - what can I do..

**Comment by peteruithoven** [comment]
Ah, I meant that it would request the height during the animation, where I assumed that the height was animated towards a hardcoded height. But I was actually wrong there, it was just an vertical offset that was animated.

**Comment by peteruithoven** [comment]
Wingpanel 2.2.3 was Released. Should appear in updates soon.
