### ISSUE TITLE
Wingpanel doesn't go black when window is maximed using a secondary monitor

### ISSUE THREAD

**Issue by surajmandalcell** [elementary/wingpanel#136]
Status : 
- Set secondary display as default
- Doesn't appear to be a stylesheet problem as i tried different themes and the problem persists.  
- Tried different apps, no progress :/
- Killed wingpanel and waited for cerbere to restart it, same thing

1st display : 1920x1080@60hz 96dpi
2nd display : 1366x768@60hz 

![wingpanel_bug](https://user-images.githubusercontent.com/11650177/42582142-07b459fc-854c-11e8-88f3-11232505c6ac.png)

**Comment by leonardo-lemos** [comment]
It happens to me if I plug a second monitor and maximize a window.
