### ISSUE TITLE
Wingpanel has a translucent black background if I login with a secondary monitor

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary/wingpanel#137]
* Log in with a secondary monitor plugged.
* See that Wingpanel has a translucent background.
* Unplug the secondary monitor.
* Change the wallpaper.
* The translucent background disappears.

**Comment by hannesschulze** [comment]
This still doesn't work for me on Juno Stable (with 3 monitors). On my notebook the font becomes dark and the background stays transparent.

![screenshot von 2018-10-17 15 11 24](https://user-images.githubusercontent.com/43932053/47088584-1dc3f200-d21f-11e8-96f6-5dc43d71f12c.png)

**Comment by lenemter** [comment]
Fixed in OS 8
