### ISSUE TITLE
With multiple VPN connections established status is incorrectly shown

### ISSUE THREAD

**Issue by skewty** [elementary/wingpanel#144]
![screenshot from 2018-09-15 16-32-22](https://user-images.githubusercontent.com/9087223/45591355-62e5c300-b905-11e8-893a-6c08ce54a476.png)

Both Houle and FHA are connected and working when I took this screenshot.

Additionally, FHA is spinning forever.
Additionally, VPN connections are acting as a radio list instead of toggle list (this is incorrect).

**Comment by naaando** [comment]
This bug should be on elementary/wingpanel-indicator-network, there are a issue about the VPN toggles already, elementary/wingpanel-indicator-network/issues#94

**Comment by skewty** [comment]
https://github.com/elementary/wingpanel-indicator-network/issues/94
^^ corrected URL

Works for me!
