### ISSUE TITLE
Wingpanel is on top of a fullscreen app

### ISSUE THREAD

**Issue by alexgleason** [elementary/wingpanel#147]
In Juno beta 2, when running EmulationStation in fullscreen mode, Wingpanel will be on top of it.

![f6uesxm](https://user-images.githubusercontent.com/3639540/46118144-1cc91300-c1d3-11e8-9113-ed43f62c8657.png)

Videos can become fullscreen and does not have this issue, so at first I thought it was a bug in EmulationStation. However, **I tested EmulationStation in Loki, and Wingpanel does not behave this way**. It stays behind EmulationStation as expected. Therefore, I believe it is a regression in Juno. It seems possible to me that other fullscreen apps will also have this problem.

**Comment by peteruithoven** [comment]
@alexgleason Did you perhaps try adding a keyboard shortcut for "Toggle Fullscreen" and using that?

**Comment by alexgleason** [comment]
While this does seem to be a regression in Juno, the problem also occurs in Ubuntu 18.04 with GNOME 3's top panel, so I'm gonna say that whatever EmulationStation is doing probably is unsupported. Not sure why it works in Loki, but whatever. :smile: Sounds like a problem for EmulationStation to fix.
