### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel#158]
it looks like there's some confusion in libwingpanel about what version it is. Apt reports 2.2.0 but meson thinks 2.0 is installed. It looks like in both CMake and Meson for libwingpanel there is its own "lib version" variable instead of following the project version. Is there a reason for bumping those separately?

See: https://github.com/elementary/wingpanel-indicator-sound/pull/76

**Comment by tintou** [comment]
lib_version is the version of the ABI and should be bumped when there is an API/ABI change. The project version is about Bugfixes and new features
