### ISSUE TITLE
Indicators get cut / disappear

### ISSUE THREAD

**Issue by kmoj86** [elementary/wingpanel#179]
![screenshot from 2018-11-29 20 58 46](https://user-images.githubusercontent.com/28702682/49243515-9c1ad300-f41e-11e8-9858-a90adf5fe76a.png)

As you can see with the night light indicator, sometimes indicators do not appear completely, and sometimes they disappear leaving only a very small blank space behind them that look like the padding from the indicators from its left and right is wider than normal.

I have no idea how to reproduce this issue because I don't know why it happens in the first place. and it's not specific to one indicator, I had it happen to bluetooth and nightlight so far.

**Comment by peteruithoven** [comment]
I'm afraid this is related to: https://github.com/elementary/wingpanel-indicator-bluetooth/issues/64
And fixed (albeit hacky) with: 
https://github.com/elementary/wingpanel/pull/174
