### ISSUE TITLE
Wingpanel disappeared in lockscreen

### ISSUE THREAD

**Issue by janxkoci** [elementary/wingpanel#181]
Hi there,

So few weeks ago I noticed my login / lock screen doesn't have a wingpanel on the top. As I remember the [announcement](https://medium.com/elementaryos/elementary-os-5-juno-is-here-471dfdedc7b3) it should have been there the same way as I have it after login. Indicators working and everything. I even remember it was there for a few days after installing Juno. But it's not there anymore.

Maybe it's intentional, maybe it's a bug, so I post it here, you tell me :) I don't really miss it that much, as it was pretty much useless even in Loki where it at least appeared. Tha battery indicator was informative, but that's about it. Sound? No need, as my music paused whenever I locked the screen. Clock are big and hard-to-miss on the lockscreen. The rest I never cared.

However if there would be plans to bring it back, I would love to have the ability to click (or other way to interact with) the battery indicator to change my brightness on the login / lockscreen. Often I turn on my laptop in different light conditions than when I put it asleep / turn it off. However for this to work I assume there needs to be the panel first. So - is there a plan to fix this bug or it's not a bug?

Thanks for the awesome work you do with this OS.

**Comment by worldofpeace** [comment]
This actually has been reported at https://github.com/elementary/greeter/issues/178 since this sounded like an issue with the greeter. Though I'm starting to doubt that too.

**Comment by peteruithoven** [comment]
Yeah I'm afraid this is a duplicate.

**Comment by janxkoci** [comment]
Ah sorry, I searched here, didn't realize it could be reported against other project.
