### ISSUE TITLE
Dropbox can't display on top panel.

### ISSUE THREAD

**Issue by jade28** [elementary/wingpanel#183]
Hi guys!
I have been this issue on `Juno 5.0`, `Loki 0.4` work well.
Thanks! 🙏

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/wingpanel/issues/96
Please search in the issue queue for existing issues next time.

**Comment by jade28** [comment]
Thanks @peteruithoven  🙏.
