### ISSUE TITLE
Notifications cleared after opening and closing notification popover

### ISSUE THREAD

**Issue by EbonJaeger** [elementary/wingpanel#185]
This behavior seems very un-intuitive as the user did not do anything to explicitly clear notifications. This can be frustrating if, after receiving a notification, the user wants to check something before going to the application. Or in another instance, there are notifications from multiple applications and you want to deal with one set before dealing with the others. Once the notification popover is closed however, all of that is lost.

For example, in Windows 10, notifications remain in the notification center after closing and reopening, but the indicator changes to reflect no new notifications.

**Comment by EbonJaeger** [comment]
....And it seems that https://github.com/elementary/wingpanel-indicator-notifications is actually the correct place for this. Are you guys able to move this, or should I re-do it?

**Comment by EbonJaeger** [comment]
Well I can't reproduce it anyway so I guess its a moot point.

**Comment by donadigo** [comment]
If the issue happens again, yes, the link above is the right one for filling it.
