### ISSUE TITLE
bluetooth is re-enabled after waking from suspend

### ISSUE THREAD

**Issue by renderorange** [elementary/wingpanel#188]
steps to reproduce:
disable bluetooth in wingpanel
suspend
wake
bluetooth is re-enabled

**Comment by peteruithoven** [comment]
Thanks for the report, but I'm afraid this has nothing to do with the Wingpanel (or the bluetooth indicator).

**Comment by renderorange** [comment]
Is there another bug report for this issue that is in the correct area?  If not, what area should it be opened in?

**Comment by peteruithoven** [comment]
Not sure, these seem related:
https://github.com/elementary/switchboard-plug-bluetooth/issues/21
https://github.com/elementary/wingpanel-indicator-bluetooth/issues/7
https://elementaryos.stackexchange.com/questions/17618/bluetooth-keeps-getting-turned-off-at-wake-up
https://elementaryos.stackexchange.com/questions/10036/bluetooth-turns-off-after-reboot

**Comment by renderorange** [comment]
Thanks for the info!

**Comment by 4jNsY6fCVqZv** [comment]
@peteruithoven The issue is still relevant. Any idea how to solve this?
