### ISSUE TITLE
Application topbar goes a few pixels under Wingpanel

### ISSUE THREAD

**Issue by stsdc** [elementary/wingpanel#191]
This happens every time after start up:
![zrzut ekranu z 2019-01-29 16 07 58](https://user-images.githubusercontent.com/6031763/51917701-66737580-23e0-11e9-81c9-1a50b734cb25.png)
After `killall wingpanel`:
![zrzut ekranu z 2019-01-29 16 08 42](https://user-images.githubusercontent.com/6031763/51917702-670c0c00-23e0-11e9-8076-ff9cc0d20155.png)

**Comment by peteruithoven** [comment]
I've been noticing this as well sometimes. 

I'm pretty sure it has something to do with this animation:
https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L76-L94
If I increase that timeout interval to `1000 / panel_height` it doesn't seem to happen anymore.
```
Timeout.add (1000 / panel_height, animation_step);
```

**Comment by arshubham** [comment]
Duplicate for https://github.com/elementary/wingpanel/issues/130

**Comment by peteruithoven** [comment]
Thanks @arshubham I knew it existed but couldn't find it anymore. I'll move my comment there.
