### ISSUE TITLE
Frequently freezes after interacting with the Applications menu or indicators

### ISSUE THREAD

**Issue by Xyaneon** [elementary/wingpanel#20]
*(This is a followup to something I posted about on Google+ [here][1], following the advice of @cassidyjames  .)*

I am using the stable release of elementary OS 0.4 Loki for the past couple of days now, and the only major issue I have run into is frequent freezing from Wingpanel. This seems to start only after I sometimes click on the Applications menu or one of the indicators, in which case the panel freezes and nothing happens. Occasionally, I will also get a popup window telling me that Wingpanel is unresponsive and asking me if I want to force quit it. Sometimes if I continue using other parts of my desktop normally after the issue starts, the whole desktop will become unresponsive to input (i.e., can still move the mouse cursor, but cannot click anything).

If I then log into a tty and issue the following command:

```bash
killall wingpanel
```

...Wingpanel of course goes away, but at least the rest of my desktop becomes responsive again. Wingpanel might come back again after several moments, at which point it behaves normally again until the issue reoccurs in several minutes to half an hour or so.

A few additional notes:

- It should be noted that I am using a Logitech mouse and solar keyboard with the Unifying wireless receiver, but I have not installed the Solaar app yet.
- I did check the ISO's sha256sum after downloading it, and installed it using UNetbootin with a USB flash drive as per the [installation instructions][2].
- This is on a desktop computer with a 64-bit Intel processor and integrated Intel graphics.
- I downloaded the latest updates through AppCenter and rebooted my machine, which did not seem to help.

I can provide additional information regarding my setup as requested.

[1]: https://plus.google.com/+ChristopherHorton/posts/GWvtQk8qaUk
[2]: https://elementary.io/docs/installation#install-on-ubuntu

**Comment by Philip-Scott** [comment]
Can you take a screenshot of your desktop, with all your indicators? It might not be wingpanel's fault but a third party indicator/app messing with it

**Comment by WarriorIng64** [comment]
@Philip-Scott Here you go. No third-party indicators up there as far as I know:

![screenshot from 2017-04-05 20-44-52](https://cloud.githubusercontent.com/assets/3268365/24732781/241f4b00-1a41-11e7-852c-05bf3fc8c041.png)

Some additional info, in case you're wondering:

- As far as third-party applications, all I've gotten around to installing so far are Google Chrome, Mozilla Firefox, LibreOffice, wxBanker and Git.
- I changed the wallpaper to something from GNOME-Look, as well as my user account picture.
- I connected to a network laser printer through System Settings.

Otherwise, everything else is at its preinstalled defaults.

**Comment by WarriorIng64** [comment]
Hate to bump, but is there any progress on this? I've been keeping my system up-to-date, but Wingpanel continues to lock up on me every few minutes or so, even when not interacted with. It seriously affects the usability of my system when I can't launch applications or interact with system tray indicators when I need to.

**Comment by davidmhewitt** [comment]
You may be able to get some useful debugging information out of wingpanel by doing the following:

```
killall cerbere
killall wingpanel
wingpanel -d
```

There are quite a few errors and warnings in wingpanel on startup, but if anything appears in the output around the time it crashes, it might be useful for us in debugging the issue.

**Comment by peteruithoven** [comment]
@Xyaneon could this be related to https://github.com/elementary/wingpanel-indicator-power/issues/15

**Comment by Xyaneon** [comment]
@peteruithoven Perhaps? But I'm not using elementary OS on my desktop computer anymore, so I am not able to test whether using the system without the Unifying receiver changes anything.

**Comment by peteruithoven** [comment]
Although it's applications specific @donadigo created a possible fix: https://github.com/elementary/applications-menu/pull/191
I don't think it's useful to keep this issue open when we have so little information and without someone who can reproduce the issue.
