### ISSUE TITLE
Focus newly started app

### ISSUE THREAD

**Issue by peteruithoven** [elementary/wingpanel#205]
Digging into [Apps are not in focus after launching from application menu #19](https://github.com/elementary/applications-menu/issues/19) I found this logic:

https://github.com/elementary/wingpanel/blob/25af8fecfd3738f2b7b0f327865e5f72a6a937d5/src/PanelWindow.vala#L155-L168

I'm afraid this steals the focus from the newly launched app. 
Does anyone have any idea how to disable this restore_window request when a new app is launched?

**Comment by davidmhewitt** [comment]
The `remember_window`, `restore_window` logic seems a little weird to me. Surely it would be better to listen for focus changes and always have the "remembered" window be the last focused window excluding wingpanel.

**Comment by davidmhewitt** [comment]
That said, the issue at hand is likely a race condition.

Smaller, faster apps manage to open their window and grab focus before this code restores the (wrong) previously focused window. Whereas slower apps take focus after the previously focused window has been given focus back.

**Comment by peteruithoven** [comment]
Interesting! 

Tricky, as far as I can find on valadoc there is no global focus change listener?
We could listen on the window that currently has focus for [focus_out_event](https://valadoc.org/gtk+-3.0/Gtk.Widget.focus_out_event.html) but I'm not sure that event includes the window that gained the focus.

**Comment by davidmhewitt** [comment]
The `wingpanel-interface` code that handles this remembering of window focus is a Gala plugin. I imagine that a plugin inside the Window Manager might be able to register for window focus gained/lost events, although I'm not 100% sure since it's a while since I looked at Gala.

**Comment by peteruithoven** [comment]
Looking through the mutter bindings there doesn't seem to be a focus changed or even a `focus_out event`. 
https://github.com/elementary/wingpanel/blob/master/vapi/libmutter.vapi
But then again I might not understand how to properly search for this.
