### ISSUE TITLE
Background isn't totally transparent anymore.

### ISSUE THREAD

**Issue by jersonlatorre** [elementary/wingpanel#207]
When there is no window maximized, wingpanel background is not 100% transparent.

**Comment by peteruithoven** [comment]
Thanks for the report but please clarify. Did it used to? Could you include a screenshot? You do know the wingpanel background adapts to the wallpaper color?

**Comment by jersonlatorre** [comment]
![DeepinScreenshot_Desktop_20190427111539](https://user-images.githubusercontent.com/5032737/56852281-d198ef00-68de-11e9-86f6-06c73a9f3b8e.png)

Until the last upgrade, only the font color adapted to the wallpaper. Now the background adapts too and creates that dark band behind. Is it a bug or a new feature? 

Thanks for reply!

**Comment by romdef** [comment]
Same problem since the last system update (same result from a fresh install after installing updates).
![Capture d'écran du 2019-04-27 20 18 43](https://user-images.githubusercontent.com/183035/56853746-4cd4c200-692c-11e9-9b17-e3e6b24704c2.jpeg)

**Comment by janxkoci** [comment]
It's not a feature, it's a bug. I have the same result as romdef, it's so ugly I had to change wallpaper.

**Comment by janxkoci** [comment]
OK I tested it little bit further and it's **only affected in the light variant** - the darkish SpaceX wallpaper has fully transparent wingpanel.

![Snímek z 2019-04-28 13-51-37](https://user-images.githubusercontent.com/19331850/56863935-f19ee000-69bc-11e9-9b25-190886f63a51.png)

**Comment by kr428** [comment]
Adding myself to that. I always had transparency issues with wingpanel on my multi-monitor setup because of https://github.com/elementary/wingpanel/issues/184; but this time it seems even worse. Using a light custom wallpaper.

![Screenshot von 2019-04-29 07 58 45](https://user-images.githubusercontent.com/685879/56878489-aafcc480-6a54-11e9-99ad-5c9860817bbc.png)

**Comment by peteruithoven** [comment]
I'm assuming this started happening since Wingpanel 2.2.4 which was released 24 april? 
More info on releases: https://github.com/elementary/wingpanel/releases

The weird thing is that there have been very few changes:
Changes between 2.2.3 and 2.2.4: https://github.com/elementary/wingpanel/compare/2.2.3...2.2.4
Changes between 2.2.2 and 2.2.3: https://github.com/elementary/wingpanel/compare/2.2.2...2.2.3

**Comment by kr428** [comment]
Not really sure actually. wingpanel on my system is 2.2.3 it seems, see below. Unfortunately, it's not that easy to downgrade to an "older" version as they don't seem to be in the repos anymore. Likewise, as far as I see, wingpanel on my installation was upgraded on April 25, in the early morning, and I am almost completely sure this wasn't an issue until earlier today (April 29)...


kr@kaleid:~$ apt-cache policy wingpanel
wingpanel:
  Installiert:           2.2.3+r264+pkg41~ubuntu5.0.1
  Installationskandidat: 2.2.3+r264+pkg41~ubuntu5.0.1
  Versionstabelle:
 *** 2.2.3+r264+pkg41~ubuntu5.0.1 500
        500 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by janxkoci** [comment]
For me the change happened after I cold-booted on 28th of April. The day before I installed some updates, don't remember exactly which packages (is there a way to check?), everything was fine and I shut down the laptop in the end of the day. The next day, on Sunday, I was greeted with that ugly wingpanel.

**Comment by peteruithoven** [comment]
I've added some logs  (how to: [OS Dev](https://elementary.io/docs/code/os-dev) > Debug logs) to https://github.com/elementary/wingpanel/blob/master/wingpanel-interface/BackgroundManager.vala#L164-L207 
And I noticed it finds the following 3 wallpapers "busy" in enough to use the TRANSLUCENT_... variant, which seems weird.
![Screenshot from 2019-04-29 18-07-54@2x](https://user-images.githubusercontent.com/523210/56909990-c47c2b80-6aa9-11e9-93b4-43af4e25bb20.png)

**Comment by kr428** [comment]
Thanks for pointing to the debugging tutorial, so far I actually missed this. :) Been reading through that bg_is_busy code before, actually, and wondered whether, for such cases, at least a hidden switch to make the user override this algorithm would generally be a viable workaround. ;)

Plus: I don't see changes to that algorithm in the given time frame, and I haven't changed my wallpaper in between. Maybe any of the dependencies (Gala.WM, CoglFixes) in Utils#get_background_color_information() has changed behaviour recently?

**Comment by janxkoci** [comment]
My idea was some theme changes - could it be the culprit?

**Comment by es28vip** [comment]
I use this method to modify  restore the original state.
[](url)https://github.com/elementary/wingpanel/issues/89#issuecomment-370198512

**Comment by jersonlatorre** [comment]
@es28vip, thanks! trying a little bit more finally this works to me:

```css
.panel.translucent {
  background-color: transparent;
}
```

**Comment by es28vip** [comment]
@jersonlatorre  I'm glad I could help you.

**Comment by kgrubb** [comment]
A quick update, it looks like gala and wingpanel aren't the culprit here. Installing `elementary-sdk` seems to reliably replicate this issue, so the problem was most likely introduced via installing or upgrading one of the packages included in the elementary-sdk bundle (:tada: thanks @peteruithoven for the discovery! :tada:). 

His comment (from slack):
> In an vm started from an iso from 2018-01-16 when I specifically update wingpanel or gala the issue doesn't appear... (while when I install the elementary-sdk it did)

**Comment by peteruithoven** [comment]
When I create a fresh vm from that 2018-01-16 iso and just update the issue also appears, meaning it's one of these packages:
```
The following NEW packages will be installed:
  bubblewrap htop libllvm7 libwayland-egl1 linux-headers-4.15.0-48
  linux-headers-4.15.0-48-generic linux-image-4.15.0-48-generic
  linux-modules-4.15.0-48-generic linux-modules-extra-4.15.0-48-generic
  python3-netifaces
The following packages will be upgraded:
  apache2-bin appcenter appcenter-casper appstream apt apt-config-icons
  apt-config-icons-hidpi apt-config-icons-large apt-config-icons-large-hidpi
  apt-utils audience avahi-autoipd avahi-daemon base-files bind9-host
  binutils binutils-common binutils-x86-64-linux-gnu browser-plugin-evince
  bsdutils busybox-initramfs busybox-static capnet-assist console-setup
  console-setup-linux cpp cpp-7 cups cups-bsd cups-client cups-common
  cups-core-drivers cups-daemon cups-ipp-utils cups-ppdc cups-server-common
  curl desktop-file-utils dirmngr disable-light-locker distro-info-data
  dnsutils dpkg dpkg-dev e2fsprogs elementary-artwork elementary-desktop
  elementary-icon-theme elementary-minimal elementary-standard
  elementary-theme evince evince-common fdisk file fonts-noto-color-emoji
  friendly-recovery g++ g++-7 gcc gcc-7 gcc-7-base gcc-8-base gettext
  gettext-base ghostscript ghostscript-x gir1.2-gtk-3.0
  gir1.2-javascriptcoregtk-4.0 gir1.2-nm-1.0 gir1.2-nma-1.0
  gir1.2-packagekitglib-1.0 gir1.2-webkit2-4.0 gkbd-capplet gnome-bluetooth
  gnome-control-center-faces gnome-desktop3-data gnome-settings-daemon
  gnome-settings-daemon-schemas gnupg gnupg-l10n gnupg-utils gparted gpg
  gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm gpgv grub-common
  grub-pc grub-pc-bin grub2-common gstreamer1.0-alsa gstreamer1.0-gl
  gstreamer1.0-packagekit gstreamer1.0-plugins-base
  gstreamer1.0-plugins-base-apps gstreamer1.0-tools gstreamer1.0-x
  gtk-update-icon-cache gvfs gvfs-backends gvfs-bin gvfs-common gvfs-daemons
  gvfs-fuse gvfs-libs im-config indicator-application initramfs-tools
  initramfs-tools-bin initramfs-tools-core io.elementary.camera
  io.elementary.code irqbalance keyboard-configuration kmod krb5-locales
  language-pack-de language-pack-fr language-pack-gnome-de
  language-pack-gnome-fr language-pack-gnome-nl language-pack-gnome-pl
  language-pack-gnome-sv language-pack-nl language-pack-pl language-pack-sv
  language-selector-common libappstream4 libapt-inst2.0 libapt-pkg5.0
  libarchive13 libasan4 libasound2 libasound2-data libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libavahi-core7
  libavahi-glib1 libbind9-160 libbinutils libblkid1 libcaca0
  libcairo-gobject2 libcairo2 libcc1-0 libcilkrts5 libcodecore0
  libcogl-common libcogl-pango20 libcogl-path20 libcogl20 libcom-err2
  libcups2 libcupscgi1 libcupsimage2 libcupsmime1 libcupsppdc1
  libcurl3-gnutls libcurl4 libdbusmenu-glib4 libdbusmenu-gtk3-4
  libdns-export1100 libdns1100 libdpkg-perl libdrm-amdgpu1 libdrm-common
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libegl-mesa0
  libegl1-mesa libevdocument3-4 libevview3-3 libexiv2-14 libext2fs2 libfdisk1
  libgbm1 libgcc-7-dev libgcc1 libgd3 libgda-5.0-4 libgda-5.0-common
  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglib2.0-0 libglib2.0-bin
  libglib2.0-data libglx-mesa0 libgnome-bluetooth13 libgnome-desktop-3-17
  libgnomekbd-common libgnomekbd8 libgomp1 libgranite-common libgranite5
  libgs9 libgs9-common libgssapi-krb5-2 libgstreamer-gl1.0-0
  libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-bin
  libgtk-3-common libgtksourceview-3.0-1 libgtksourceview-3.0-common
  libgweather-3-15 libgweather-common libidn11 libirs160 libisc-export169
  libisc169 libisccc160 libisccfg160 libitm1 libjavascriptcoregtk-4.0-18
  libk5crypto3 libkmod2 libkrb5-3 libkrb5support0 libldap-2.4-2
  libldap-common libldb1 liblsan0 liblwres160 libmagic-mgc libmagic1
  libmaya-calendar0 libmount1 libmpx2 libmutter-2-0 libnautilus-extension1a
  libnm-glib4 libnm-util2 libnm0 libnma0 libnoise-core0 libnss-systemd
  libnss3 libntfs-3g88 libnuma1 libpackagekit-glib2-18 libpam-modules
  libpam-modules-bin libpam-runtime libpam-systemd libpam0g
  libpantheon-files-core0 libpantheon-files-widgets0 libparted-fs-resize0
  libparted2 libpci3 libperl5.26 libplank-common libplank1 libplymouth4
  libpng16-16 libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0
  libpoppler-glib8 libpoppler73 libpulse-mainloop-glib0 libpulse0 libpulsedsp
  libpython2.7 libpython2.7-minimal libpython2.7-stdlib libpython3-stdlib
  libpython3.6 libpython3.6-minimal libpython3.6-stdlib libqt5core5a
  libqt5dbus5 libqt5gui5 libqt5network5 libqt5widgets5 libquadmath0 libraw16
  libseccomp2 libsmartcols1 libsmbclient libss2 libssh-gcrypt-4 libssl1.0.0
  libssl1.1 libstdc++-7-dev libstdc++6 libswitchboard-2.0-0 libsystemd0
  libtiff5 libtsan0 libu2f-udev libubsan0 libudev1 libunistring2
  libupower-glib3 libuuid1 libvala-0.40-0 libwavpack1 libwayland-client0
  libwayland-cursor0 libwayland-egl1-mesa libwayland-server0 libwbclient0
  libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-37-gtk2 libx11-6 libx11-data
  libx11-xcb1 libxatracker2 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-randr0 libxcb-render0 libxcb-res0 libxcb-shape0
  libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1
  libxcb1 libxkbcommon-x11-0 libxkbcommon0 libxslt1.1 libzmq5 linux-firmware
  linux-generic linux-headers-generic linux-image-generic linux-libc-dev
  linux-signed-generic linux-signed-image-generic login man-db maya-calendar
  maya-calendar-daemon maya-calendar-plugin-caldav
  maya-calendar-plugin-google mesa-va-drivers mesa-vdpau-drivers mount
  mutter-common nautilus-data netplan.io network-manager
  network-manager-config-connectivity-ubuntu network-manager-gnome
  networkd-dispatcher noise nplan ntfs-3g openssh-client openssl packagekit
  packagekit-tools pantheon pantheon-agent-geoclue2 pantheon-agent-polkit
  pantheon-calculator pantheon-files pantheon-greeter
  pantheon-online-accounts-plugin-fastmail
  pantheon-online-accounts-plugin-lastfm pantheon-online-accounts-plugin-mail
  pantheon-photos pantheon-shell pantheon-terminal parted passwd pciutils
  perl perl-base perl-modules-5.26 plank plymouth plymouth-label policykit-1
  poppler-utils ppp psmisc pulseaudio pulseaudio-module-bluetooth
  pulseaudio-utils python-apt-common python-ldb python-samba python2.7
  python2.7-minimal python3 python3-apport python3-apt python3-gdbm
  python3-gi python3-gi-cairo python3-httplib2 python3-minimal
  python3-problem-report python3.6 python3.6-minimal qt5-gtk-platformtheme
  rfkill samba-common samba-common-bin samba-libs screenshot-tool
  slingshot-launcher switchboard switchboard-plug-a11y switchboard-plug-about
  switchboard-plug-applications switchboard-plug-bluetooth
  switchboard-plug-datetime switchboard-plug-display
  switchboard-plug-keyboard switchboard-plug-locale
  switchboard-plug-mouse-touchpad switchboard-plug-networking
  switchboard-plug-online-accounts switchboard-plug-pantheon-shell
  switchboard-plug-power switchboard-plug-printers
  switchboard-plug-security-privacy switchboard-plug-sound
  switchboard-plug-useraccounts switchboard-plug-users systemd systemd-sysv
  tar thermald tzdata ubiquity ubiquity-frontend-gtk
  ubiquity-slideshow-elementary ubiquity-ubuntu-artwork ubuntu-drivers-common
  ubuntu-keyring ubuntu-minimal udev ufw upower ureadahead usbmuxd util-linux
  uuid-runtime wget wingpanel-indicator-bluetooth
  wingpanel-indicator-datetime wingpanel-indicator-keyboard
  wingpanel-indicator-network wingpanel-indicator-nightlight
  wingpanel-indicator-notifications wingpanel-indicator-power
  wingpanel-indicator-session wingpanel-indicator-sound wpasupplicant
  xdg-utils xserver-common xserver-xorg-core xserver-xorg-legacy
```

**Comment by peteruithoven** [comment]
This wallpaper (which should show a transparent wingpanel):
![Screenshot from 2019-05-06 18-55-39@2x](https://user-images.githubusercontent.com/523210/57241117-927e4280-7030-11e9-9770-a370738da6f6.png)
Gives:
```
bk_color_info.luminance_variance: 3157,448833
luminance_std: 56,191181
bk_color_info.mean_luminance: 204,062616
bk_color_info.mean_acutance: 18,081596
STD_THRESHOLD: 45,000000
LUMINANCE_THRESHOLD: 180,000000
ACUTANCE_THRESHOLD: 8,000000
bk_color_info.mean_luminance + 1.645 * luminance_std: 296,497109
// These conditionals are triggered:
luminance_std > STD_THRESHOLD
bk_color_info.mean_luminance + 1.645 * luminance_std > LUMINANCE_THRESHOLD
bk_color_info.mean_acutance > ACUTANCE_THRESHOLD
```

This wallpaper (which should show a non transparent wingpanel):
![Screenshot from 2019-05-06 18-55-32@2x](https://user-images.githubusercontent.com/523210/57241169-a9bd3000-7030-11e9-9ecb-38bfc9560b77.png)
Gives:
```
bk_color_info.luminance_variance: 122,468332
luminance_std: 11,066541
bk_color_info.mean_luminance: 24,284012
bk_color_info.mean_acutance: 7,254785
STD_THRESHOLD: 45,000000
LUMINANCE_THRESHOLD: 180,000000
ACUTANCE_THRESHOLD: 8,000000
// These conditionals are triggered:
bk_color_info.mean_luminance < LUMINANCE_THRESHOLD
```

**Comment by peteruithoven** [comment]
Looking at `Utils.get_background_color_information`:
https://github.com/elementary/wingpanel/blob/687b3166c44894c9d0934621f30768ab8f7cc1ff/wingpanel-interface/Utils.vala#L84

There is this `CoglFixes`. 
I found 4 seemingly related packages that are upgraded: 
`libcogl-common libcogl-pango20 libcogl-path20 libcogl20`
But upgrading just those (and restarting gala) also doesn't give the issue.

**Comment by peteruithoven** [comment]
It also talks to the window manager:
https://github.com/elementary/wingpanel/blob/687b3166c44894c9d0934621f30768ab8f7cc1ff/wingpanel-interface/Utils.vala#L52

Which is and/or uses Mutter, so I updated just `mutter-common`, which didn't give the issue. Finally updating `libmutter-2-0` gives the issue. So `libmutter-2-0` is somehow the culprit here...

**Comment by kr428** [comment]
Seems you got a bit further than me digging into CoglFixes and friends. :) Well, not wanting to play devils advocate here, but given that, wouldn't it be better to either use a forked version of that mutter stuff for elementary - or give up on only automatically determining panel background/transparency and/or make this an option that can be overridden by the user (by explicitely stating or at least "correcting" the intended amount of transparency)? ;) 

(off to try to get me an elementary VM to somehow get a debug environment that doesn't trash my day-to-day working system...)

**Comment by donadigo** [comment]
@kr428 I've already brought up this point to the team, but it seems like they're not interested in that and their stance is that a fork has to be maintained by someone and that it is extra work which I don't agree with given the possibilities and freedom it gives us.

**Comment by kr428** [comment]
@donadigo I actually to some degree can understand this - it's always a balance between wasting effort on maintaining forks of the same thing on one side and the risks and challenges of handling cross-team dependencies on the other. ;)

**Comment by quequotion** [comment]
Not sure if it works with Gala, but one may specify a [static color and transparency](https://wiki.archlinux.org/index.php/Pantheon#Wingpanel_transparency); there are [several ways](https://developer.gnome.org/gtk3/unstable/chap-css-overview.html#id-1.5.2.3.8.7) to specify colors.

I have a forked wingpanel with the automatic colorization and transparency features [patched out](https://aur.archlinux.org/packages/wingpanel-standalone-git/#pinned-685036), for use with window managers other than Gala.

They are nifty features, but I don't find them all that useful. It's not just that I don't use Gala, but that I rarely change my background (most of the time default, black nothingness).

I set wingpanel's background to black and 50% transparent--rgba(0,0,0,0.5)--and have no complaints.

**Comment by virtualracer** [comment]
Found a simple workaround:
create a `gtk.css` file inside `~/.config/gtk-3.0/` and write this inside:

`/*********************
 * wingpanel support *
 ********************/

.panel {
    background-color: transparent;
    transition: all 100ms ease-in-out;
}

.panel.maximized {
    background-color: #000;
}
`
save this and run `pkill wingpanel`
enjoy

**Comment by janxkoci** [comment]
@virtualracer this was already fixed months ago. Also note that wingpanel has *adaptive transparency* based on wallpaper, not just simple "always-on"..

**Comment by quequotion** [comment]
>wingpanel has _adaptive transparency_ based on wallpaper, not just simple "always-on"

I'd just like to chime in to note that is a feature dependant on the Gala window manager. Not something most users of elementary OS need concern themselves with, but wingpanel's background is static with other window managers.

Also, if a static background is desired, CSS can be used to achieve that, even when using Gala (there are some additional selectors that may need to be overriden).

**Comment by kr428** [comment]
Something I noticed that might be related to that: There is a bunch of images on my device (like photos off my digital camera) that, in file manager, appear with a "black" border on top and bottom in thumbnails, but when I open these in any image viewer, the black border is not actually there. 

Whenever I try to set one of these pictures as wallpaper, I can be sure wingpanel transparency will be messed up, even in lates 5.1 releases. Opening one of these files in gimp, cropping it a bit and saving it again before setting it as a wallpaper will fix this issue. As it is reproducible, I think these things are somewhat related, but I so far have no clue why and how. :) 

![pics-border](https://user-images.githubusercontent.com/685879/75032242-5e351f00-54a8-11ea-8a2e-8532c76ba2a9.png)

**Comment by quequotion** [comment]
>when I open these in any image viewer, the black border is not actually there.
> Whenever I try to set one of these pictures as wallpaper, I can be sure wingpanel transparency will be messed
>cropping it a bit and saving it again before setting it as a wallpaper will fix this issue

Do those images have _transparent_ borders? ie, there's nothing visible in viewing apps but gimp opens an editing window a little larger than the picture with the gaps filled in with a grey, checkered background? 

Thumbnailers often render transparency as black, say if the thumbnail's image format does not support tranparency. 

Just a theory, but maybe wingpanel & gala don't know what to do when wingpanel is drawn over a transparent background (note that the desktop can't really render an invisible hole either, so there will be a fill-in color such as black, blue, or another configured background color in the gaps).

**Comment by kr428** [comment]
That was my first idea as well but apparently it's not the case - opening these images in gimp just shows me the full image and correct size ratio, no borders whatsoever. Thumbnails in Files differ though. In wonder whether that might be part of this problem after reading through the algorithm and seeing it uses certain features of the image to determine how to set the panel background - obviously this might come to a different result if it uses "flaky" data because it gets the images wrong...?

Am 21. Februar 2020 19:05:45 schrieb Que Quotion <notifications@github.com>:

**Comment by quequotion** [comment]
>"flaky" data
I haven't checked the code, does it use any EXIF data?

**Comment by kr428** [comment]
>
> I haven't checked the code, does it use any EXIF data?
>

I don't think so, at least not by looking at the code. See this (https://github.com/elementary/wingpanel/issues/207#issuecomment-487643930) a bit earlier in this thread; Peter also linked to the relevant code lines here. That seems to work by using this method (https://github.com/elementary/wingpanel/blob/7a17fb1411cb11026f2fe955b0af6c06e582e1e3/wingpanel-interface/Utils.vala#L50) to gather information about the colors used in the background image/texture. Maybe I'll find ways to dive deeper into this at some point.

**Comment by fnune** [comment]
I'm having a similar issue right now. It works just fine (full transparency) on backgrounds that are slightly darker:

![screenshot](https://user-images.githubusercontent.com/16181067/99909987-ee301f80-2ceb-11eb-9eab-725a322c6bc8.png)

However, on lighter backgrounds, where there should be full transparency as well (with grey text), I see this:

![screenshot_1](https://user-images.githubusercontent.com/16181067/99909999-0869fd80-2cec-11eb-9af6-ff7dd82186cd.png)

This has been the case only recenly. Maybe I can try to find out which packages were updated?

**Comment by janxkoci** [comment]
I just set the same wallpaper as you @fnune and I don't see it:

![Snímek z 2020-11-23 13-24-59](https://user-images.githubusercontent.com/19331850/99961835-656abf80-2d8f-11eb-855f-4bd4ff04df41.png)

**Comment by fnune** [comment]
Hey, thanks for testing that!

I made some changes that could have introduced my bug. I created a `~/.config/gtk-3.0/gtk.css` and added some stuff, but later on removed the file.

I believe the file didn't exist before I created it and made those changes.

**Comment by janxkoci** [comment]
Well I don't have that file on my system. My system is quite new, I got it preinstalled on a new Slimbook last week ;)

**Comment by fnune** [comment]
Could having `gnome-tweaks` installed have anything to do with my problem?

**Comment by fnune** [comment]
Nope, set everything back to defaults and removed `gnome-tweaks`, logged out and back in, and the problem persists:

![image](https://user-images.githubusercontent.com/16181067/100393913-93742c00-303b-11eb-8a33-1b45cfa43743.png)

**Comment by fnune** [comment]
Found it!

It's only happening when I connect my external monitor and set it as a primary monitor. Filed a new issue:

https://github.com/elementary/wingpanel/issues/358

**Comment by whitewolfAK47** [comment]
> Found a simple workaround: create a `gtk.css` file inside `~/.config/gtk-3.0/` and write this inside:
> 
> `/*********************` `* wingpanel support *` ` ********************/` `.panel {` ` background-color: transparent;` ` transition: all 100ms ease-in-out;` `}` `.panel.maximized {` ` background-color: #000;` `}`
> 
> save this and run `pkill wingpanel` enjoy

i tried this... i am in endeavouros and have this problem. nothing has worked for me. :-(
