### ISSUE TITLE
Wingpanel hangs unexpectedly.

### ISSUE THREAD

**Issue by aggalex** [elementary/wingpanel#217]
After the last update, I've noticed two in times in one day that Wingpanel went unresponsive:

- Buttons (indicators, time, and applications menu) don't work
- Unmaximizing the window doesn't revert the panel to semi-opaque status and it just has an opaque black background

Current workaround: Kill the wingpanel with `killall wingpanel`. Cerbere will bring it back
Maximized app: Firefox (Didn't have anything else maximized today)

**Comment by aggalex** [comment]
3rd time
You can see it's totally black background and it's unresponsiveness in the screen record below (i was clicking on the time indicator):

![output](https://user-images.githubusercontent.com/11951328/58768432-bbe4ac80-85a3-11e9-9cc6-133c86d2d23d.gif)

**Comment by donadigo** [comment]
Perhaps this has to do with: https://github.com/elementary/applications-menu/issues/190 (which was fixed in master)?. Does specifically opening the menu freeze the panel or the panel freezes periodically without any action?

**Comment by aggalex** [comment]
I don't know. I usually use the ⌘ key. All I ever noticed it that when i needed it (mainly applications menu through the ⌘ key) the panel did not respond.

**Comment by tuxiano** [comment]
I'm experiencing the same issue. Killing wingpanel does not help.

journalctl output:
```
Sep 05 20:39:15 mifcom vlc.bin[7128]: Failed to load module "pantheon-filechooser-module"
Sep 05 20:39:15 mifcom vlc.bin[7128]: Failed to load module "canberra-gtk-module"
Sep 05 20:39:15 mifcom vlc.bin[7128]: Failed to load module "canberra-gtk-module"
Sep 05 20:39:15 mifcom io.elementary.cerbere.desktop[2459]: QIBusPlatformInputContext: invalid portal bus.
Sep 05 20:39:15 mifcom io.elementary.cerbere.desktop[2459]: QApplication: invalid style override passed, ignoring it.
Sep 05 20:39:15 mifcom io.elementary.cerbere.desktop[2459]:     Available styles: Breeze, Windows, Fusion
Sep 05 20:39:16 mifcom io.elementary.cerbere.desktop[2459]: libEGL warning: DRI2: failed to authenticate
Sep 05 20:39:16 mifcom io.elementary.cerbere.desktop[2459]: [00007f5438c14e60] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  430.26  Tue Jun  4 17:43:17 CDT 2019 for hardware decoding
Sep 05 20:39:22 mifcom io.elementary.cerbere.desktop[2459]: QObject::~QObject: Timers cannot be stopped from another thread
Sep 05 20:39:37 mifcom io.elementary.f[7181]: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues
Sep 05 20:40:00 mifcom gala.desktop[2445]: Failed to register: Zeitüberschreitung wurde erreicht
Sep 05 20:40:00 mifcom gala[2445]: clutter_actor_add_effect_with_name: assertion 'CLUTTER_IS_ACTOR (self)' failed
Sep 05 20:40:34 mifcom gala.desktop[2445]: Failed to register: Zeitüberschreitung wurde erreicht
Sep 05 20:40:35 mifcom gala.desktop[2445]: Failed to register: Zeitüberschreitung wurde erreicht
Sep 05 20:43:21 mifcom io.elementary.t[7796]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
```

**Comment by aggalex** [comment]
Btw this has been long fixed 4 me, I guess I will just let it open for @tuxiano.

**Comment by tuxiano** [comment]
Since the wingpanel did freeze frequently I had to reinstall eos. Now, its working again. Hope it won't happen again.

**Comment by aggalex** [comment]
Closing the issue, since nobody in the discussion has the problem anymore.
