### ISSUE TITLE
Indicators lose focus when when navigating between them

### ISSUE THREAD

**Issue by terrakok** [elementary/wingpanel#220]
It happens only if some window opened on current workspace

I think it issue connected with  #553 

![Запись экрана от 2019-06-13 14 45 26](https://user-images.githubusercontent.com/3532155/59430976-65217300-8dec-11e9-91c5-e3c75aad47bb.gif)

**Comment by peteruithoven** [comment]
Good catch! I think both issues are related to whether the Wingpanel (this includes the indicator popovers) has focus. When the window where radio buttons switches are in doesn't have focus they turn gray, you'll see this in other apps as well. 

There was one recent focus related change: https://github.com/elementary/wingpanel/pull/206.

**Comment by peteruithoven** [comment]
This issue also happens when cycling through the indicators using the keyboard: <kbd>Ctrl</kbd> + <kbd>Tab</kbd> / <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd>.

**Comment by 4jNsY6fCVqZv** [comment]
@donadigo This fix hasn't been released yet, has it? The issue is still present!

**Comment by peteruithoven** [comment]
@4jNsY6fCVqZv The fix was merged on 3 juli 2019: 
https://github.com/elementary/wingpanel/pull/222#event-2455957746
The last Wingpanel release was on Jun 5 2019:
https://github.com/elementary/wingpanel/releases

**Comment by 4jNsY6fCVqZv** [comment]
@peteruithoven Thanks for your feedback!
How do you decide when to make a new Wingpanel release?
