### ISSUE TITLE
Icons in the right part of the Wingpamel are not in the line any more

### ISSUE THREAD

**Issue by Cluster19** [elementary/wingpanel#23]
http://savepic.ru/13707888.png
 The screen of the issue

**Comment by matzipan** [comment]
Hello, 

Are you on the latest version? Are you on Loki Stable or Loki Daily? Can you do a `apt show wingpanel` and paste the message here? 

Do you remember any other packages which have updated?

**Comment by cassidyjames** [comment]
It looks like the language/input indicator is making the panel grow vertically.

**Comment by danrabbit** [comment]
Closing as "Invalid" for wingpanel and now tracking against the keyboard indicator

**Comment by Cluster19** [comment]
2matzipan: 
1) Loki Stable
2) apt show wingpanel
Package: wingpanel
Version: 2.0.2~r173-0+pkg31~ubuntu0.4.1
Priority: extra
Section: x11
Maintainer: Cody Garver <cody@elementary.io>
Installed-Size: 402 kB
Provides: indicator-renderer
Depends: libwingpanel-2.0-0 (= 2.0.2~r173-0+pkg31~ubuntu0.4.1), dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.4), libclutter-1.0-0 (>= 1.10.0), libcogl20 (>= 1.17.4), libgala0, libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.39.90), libgranite3 (>= 0.2.0), libgtk-3-0 (>= 3.14), libmutter0g
Recommends: wingpanel-indicator-bluetooth, wingpanel-indicator-datetime, wingpanel-indicator-network, wingpanel-indicator-notifications, wingpanel-indicator-power, wingpanel-indicator-session, wingpanel-indicator-sound
Download-Size: 46,8 kB
APT-Manual-Installed: no
APT-Sources: http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial/main amd64 Packages
Description: A super sexy space-saving top panel
 A replacement for the traditional GNOME Panel, designed to be a lightweight
 container for system/application indicators and notification icons.
 Designed by elementary Project.

**Comment by danrabbit** [comment]
Locking thread because this is not an issue with wingpanel itself. Please continue conversation on the other thread
