### ISSUE TITLE
How to replace the search icon on Wingpanel

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/wingpanel#232]
How to replace the search icon on Wingpanel, the old version can be rebuilt with the new icon, how to modify it in Wingpanel 2.2.5?

**Comment by cassidyjames** [comment]
I'm not sure exactly what you're asking for. The icon is set here in the Applications Menu code: https://github.com/elementary/applications-menu/blob/d1661105ddde3e5d110afbcecd82df3586ee058b/src/Slingshot.vala#L80

You could modify the source code and recompile to change how the Applications Menu appears.

**Comment by Yakumo-Yukari** [comment]
Thank you
