### ISSUE TITLE
Wingpanel missing include directory for mutter-2 and won't build

### ISSUE THREAD

**Issue by Enerccio** [elementary/wingpanel#241]
For some reason path to core mutter-2 include directory is not included in the build and it will fail to find `meta/screen.h`. I fixed it myself for the build by adding it forcefully in `meson.build`: `    c_args: ['-I/usr/include/mutter-2/mutter'] + c_flags,` but I think it should be fixed generally.

**Comment by kgrubb** [comment]
Hey @Enerccio, is this still an issue, or are you able to build now?

**Comment by lenemter** [comment]
I think this is fixed.
