### ISSUE TITLE
Search for X in Software - Don't know how to handle 'appstream://X'

### ISSUE THREAD

**Issue by TeNNoX** [elementary/wingpanel#242]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
_Not sure if issue of wingpanel or [appcenter](https://github.com/elementary/appcenter) - so I'm starting here_
The search's suggestion to "Search for X in software", results in an error from appcenter: "Don't know how to handle 'appstream://X/'"

### To Reproduce
1. Type a search in wingpanel (e.g. "peek")
2. Click on `Search for **peek** in software`
3. See error in appcenter:  `Don't know how to handle 'appstream://peek/'`

### Expected behavior
The search results.

### Screenshots or screen recordings
![Screenshot from 2019-09-26 11-21-50](https://user-images.githubusercontent.com/2084639/65681260-6a7b9400-e050-11e9-9681-b43e8e8f30c1.png)
![Screenshot from 2019-09-26 11-22-00](https://user-images.githubusercontent.com/2084639/65681266-6c455780-e050-11e9-82fe-c0aa884a2fe7.png)

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version
![Screenshot from 2019-09-26 11-26-23](https://user-images.githubusercontent.com/2084639/65681334-96971500-e050-11e9-8a32-ddf547a9f155.png)

**AppCenter**: 3.1.1+r1619+pkg77\~ubuntu5.0.1
**Wingpanel**: 2.2.5+r269+pkg42\~ubuntu5.0.1
**appstream**: 0.12.6-0elementary5.0.1

**Comment by tintou** [comment]
It seems that you're using GNOME Software here and not elementary AppCenter and that GNOME Software is very strict with the `appstream://` scheme and do not search for things so nothing to do on our side unfortunately

**Comment by TeNNoX** [comment]
Now that you say it... true.
I didn't install it conciously.

After uninstalling that, it works.
