### ISSUE TITLE
Wingpanel 2.2.6. is ignoring .composited-indicator selector

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/wingpanel#262]
From the version 2.2.6., the Wingpanel is ignoring `.composited-indicator` selector in `apps.css`. It was a convenient way to control the gap between third party icons (Dropbox, Skype, etc.), which, by default, was always bigger than it should be.
Up to this version, this was never an issue.

OS: Vanilla ElementaryOS Juno with the latest updates as of November the 1st. Nothing compiled manually, no unstable repos of any kind, no third party themes.

Cheers.

**Comment by ochornolutskyi** [comment]
Hi. To change the distance between the icons, write your style ".composited-indicator" in "~/.config/gtk-3.0/gtk.css"

**Comment by danrabbit** [comment]
Wingpanel now contains its own CSS and no longer relies on the system stylesheet for its custom styling. This behavior is intentional

**Comment by ochornolutskyi** [comment]
> Wingpanel now contains its own CSS and no longer relies on the system stylesheet for its custom styling. This behavior is intentional

You can try my method and it works
