### ISSUE TITLE
All components in the top bar are hidden

### ISSUE THREAD

**Issue by oyamabilana** [elementary/wingpanel#271]
After installing System monitor from the App centre, the App icon, Notifications panel including other controls (battery Percentage, date, time, wife etc) on the top panel don't show. This is a clean install of "elementary OS 5.1 Hera", as of writing I've been using it for 2 hours of which it has already crashed, but that's a story for another post.

**Comment by danrabbit** [comment]
@oyamabilana Can you be more explicit about which system monitor you've installed? Have you added any PPAs or copied any Terminal commands from the internet?

**Comment by oyamabilana** [comment]
@danrabbit it's Monitor v0. 6.1 - by Stanislaw Dac. I have not added any packages whatsoever, Monitor was the first app i installed which was through the appcenter. No terminal commands by the time of the error as I was still simply using the GUI for everything. I will upload some logs if any bugs persists as I'm constantly getting bugs, unless I can list all of them under one report?

**Comment by danrabbit** [comment]
@oyamabilana I'm unable to reproduce any issue after installing Monitor by Stanislaw from AppCenter. Can you try running `wingpanel` from Terminal and copy/paste the output here?

It would be better to open separate issue reports if you are encountering a different issue so that the issue can be tracked against the correct project and assigned to the correct developer

**Comment by oyamabilana** [comment]
@danrabbit, the wingpanel was back after a hard reset. I'll post the log if I encounter it again. Or is it possible to retrieve data on the log that happened at least 15 hours ago?

**Comment by danrabbit** [comment]
Please feel free to reopen the issue if it is reproducible. Since it sounds like the issue can no longer be reproduced, I'm going to close this report as incomplete
