### ISSUE TITLE
Additional menu of the network-manager 

### ISSUE THREAD

**Issue by ochornolutskyi** [elementary/wingpanel#272]
Hello, sorry for my Ukrainian English. After reinstalling elementary os 5.1 Hera and installing "indicator-application wingpanel-indicator-ayatana"  packages, appeared an additional menu of the network-manager . when I remove these packages, the additional network-manager menu disappears and all the tray. Can I fix it?
![Снимок экрана от 2019-12-15 12-34-21](https://user-images.githubusercontent.com/46054029/70861540-f3abb400-1f37-11ea-88fc-85c115827cda.png)

**Comment by danrabbit** [comment]
This is not an issue with wingpanel, it's an issue with the extension you installed. Closing as "Out of scope" for wingpanel.

**Comment by ochornolutskyi** [comment]
okay. understand. thanks
