### ISSUE TITLE
Guys, how do I add a label to wingpanel and display it? 

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/wingpanel#275]
Is there a related example, novice vala

**Comment by stsdc** [comment]
There is literally a folder named [`sample`](https://github.com/elementary/wingpanel/tree/master/sample). :sweat_smile:

**Comment by Yakumo-Yukari** [comment]
> There is literally a folder named [`sample`](https://github.com/elementary/wingpanel/tree/master/sample) in source code. 😅
> What You want to create is called an Indicator, inside which You can place different widgets.

Thank you
