### ISSUE TITLE
How to modify the text color on wingpanel

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/wingpanel#281]
![2020-01-29 13 42 46](https://user-images.githubusercontent.com/12076232/73331198-071f9e00-429e-11ea-847e-fb6ca4fc3263.png)

Where does wingpanel modify the text color on wingpanel after the application window is maximized?

**Comment by cassidyjames** [comment]
The styling is controlled by the CSS in `data/styles/`
