### ISSUE TITLE
Wingpanel freezes after suspended

### ISSUE THREAD

**Issue by WildDash** [elementary/wingpanel#282]
After suspending the system manually or closing and opening the laptop's lid. Wingpanel just freezes and it shuts down Wi-Fi and Bluetooth. It wont let me open my apps, or any other indicator. I have to force the shutdown. Also I can't open internet based apps such as chrome or spotify idk why.

**Comment by peteruithoven** [comment]
> it shuts down Wi-Fi and Bluetooth.
Can you clarify? You wifi and bluetooth are disabled when you come out of a suspend? 
That seems unrelated to the wingpanel?

> It wont let me open my apps
You mean you can't open the applications menu? Or can you also not open apps in other ways like from the dock of using keyboard shortcuts? 

> Also I can't open internet based apps such as chrome or spotify idk why.
How did you try opening these? This also doesn't seem related to wingpanel freezing?

**Comment by peteruithoven** [comment]
This might be related to:
https://github.com/elementary/wingpanel-indicator-notifications/issues/237
https://github.com/elementary/wingpanel-indicator-notifications/pull/241

If you still experience the issue please re-open.
