### ISSUE TITLE
Esc key to close wingpanel and return to previous window

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/wingpanel#283]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Add an option to use the `Esc` key to close the wingpanel after clicking on it and return to previous window. For example, if I have Files open and I click on the WiFi (Network settings), the focus shifts to WiFi settings of course and then we should be able to use `Esc` key to close that and return focus to Files.

**Describe the solution you'd like**

Add `Esc` key functionality to return focus to previously opened window

**Comment by cassidyjames** [comment]
Interestingly this works in the date/time indicator and applications menu, so I wonder if it's up to each indicator? It makes sense to me that it would be managed by wingpanel itself, though.

**Comment by vikasnataraja** [comment]
Another thing I noticed is that when the cursor hovers over the Applications menu, it shows a preview which says "Applications" but doesn't do that when it hovers over the Date/TIme indicator or any of the ones on the top right. This is of course a separate issue and I'll probably raise a new one but might be relevant here.
![Screenshot from 2020-01-30 14-23-24](https://user-images.githubusercontent.com/46734097/73491609-3c92bd00-436c-11ea-85ae-8f106d69f722.png)

**Comment by cassidyjames** [comment]
@vikasnataraja that's entirely unrelated, but feel free to open issues on the individual indicators to add tooltips.
