### ISSUE TITLE
The wingpanel closes itself.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/wingpanel#293]
The computer is running normally but at the last 2 days, the wingpanel stop working all the time! It's possible to relaunch it using the terminal with the command "wingpanel", but it shouldn't work that way.

**Comment by peteruithoven** [comment]
This isn't much to go on I'm afraid. 

Seems similar to:
- https://github.com/elementary/wingpanel/issues/117
- https://github.com/elementary/wingpanel/issues/416
- https://github.com/elementary/wingpanel/issues/442
