### ISSUE TITLE
Cannot use function key shortcuts while context menu on plank icon is open

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/wingpanel#294]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
While a context menu on plank is open, I cannot control the system settings via function keys on my laptop.

### To Reproduce
Attach Firefox to plank
Open 2 separate Firefox windows
Right click the Firefox icon on plank
The context menu opens
Without closing the context menu, press brightness our volume modification key (on my Lenovo Laptop = <Fn>+<F3> for example)

### Expected behavior
Volume should increase and the indicator displayed on the top wingpanel.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by danrabbit** [comment]
This is a well-known limitation of x11 and effects every menu of every application. It cannot be fixed in wingpanel, therefore closing as "Out of scope"
