### ISSUE TITLE
Can't modify the style of the flaps through app.css in the theme file?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/wingpanel#301]
![2020-03-20 07 53 46](https://user-images.githubusercontent.com/12076232/77125318-6c169980-6a80-11ea-9703-2693ff2ce28d.png)

Can't modify the style of the flaps through app.css in the theme file? Modifying the code in app.css will not take effect.

When I changed the background color of .panel.maximized to pink or other colors in app.css, after maximizing the window, the background color of wingpanel was not changed to the modified color, and the background color of wingpanel was still the default black.

So is it a bug? Or did you modify its control mechanism?

**Comment by Miosame** [comment]
@Yakumo-Yukari wanted to change it too just now, the change has to happen in ~/.config/gtk-3.0/gtk.css - if the file does not exist, just create it, incl the folder `gtk-3.0`.

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari wanted to change it too just now, the change has to happen in ~/.config/gtk-3.0/gtk.css - if the file does not exist, just create it, incl the folder `gtk-3.0`.

Okay, thanks for the reply.
