### ISSUE TITLE
Wingpanel appears on dock and can be minimized

### ISSUE THREAD

**Issue by corlaez** [elementary/wingpanel#303]
## Prerequisites
- There is no particular steps to reproduce this, I just see it there. Not sure since when. 

## Describe the bug
Wingpanel appears in the dock
![Screenshot from 2020-03-27 11-59-48](https://user-images.githubusercontent.com/18663098/77775487-fa5fc200-7022-11ea-80a5-0cd3f0198370.png)
And can minimize (hide) the wingpanel at the top of the screen when clicked

This behavior is not expected and I haven't seen it before.

**Comment by danrabbit** [comment]
It looks like there was a fix committed to the network indicator that could cause this to show. I’ve make a release PR there. Possibly could be fixed once that is released

**Comment by danirabbit** [comment]
I'm going to close this since it's quite old and we also have a new method for detecting running apps
