### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by in-character** [elementary/wingpanel#314]
I use [this](https://github.com/mlibre/hide-wingpanel) 
```
#!/bin/bash
result=`ps aux | grep -i "Wingpanel" | grep -v "grep" | wc -l`
if [ $result -ge 1 ]
   then
	killall cerbere &> /dev/null
	wait
	killall wingpanel &> /dev/null
      else
        wingpanel &> /dev/null &
fi
```
to get wingpanel auto_hide.
- **problem**
It works well in os 5.1. When updating os to 5.1.3, This script need executing twice externally to get wingpanel hiden successfully when booting system.
- 
  I have checked `io.elementary.desktop.cerbere monitored-processes` is `null`. Is there anything need to configure.

**Comment by davidmhewitt** [comment]
Cerbere isn't used anymore, so the cerbere setting won't do anything, and the script hasn't been updated.

If you don't want wingpanel to autostart, remove it's autostart from /etc/xdg/autostart. Do so at your own risk though. I don't know what side effects removing components of the session has.

Closing this as it's not an issue.

**Comment by in-character** [comment]
Ater removing wingpanel, maybe the screen will stay on elementary logo forever. Maybe.

**Comment by in-character** [comment]
Is there any other setting monitering wingpanel in case of its crashing.
I guess there exists one. When running this script after booting, wingpanel restarts once.
