### ISSUE TITLE
Change the height of the Wingpanel

### ISSUE THREAD

**Issue by kooshkaki** [elementary/wingpanel#321]
One of the good things about Elementary OS version 6 is that you can change the height of the Wingpanel through the settings.
For example, you can change the height of a Wingpanel to 20 pixels. Exactly like a ‌Budgie Desktop Environment that can change the top panel.

**This feature will be great.**

**Comment by danrabbit** [comment]
This isn’t possible since the icons inside the panel are 24. The panel is already as small as it can be to fit its contents
