### ISSUE TITLE
[Proposal] Override OverlyIcons for specific applications

### ISSUE THREAD

**Issue by mostafa-saeed** [elementary/wingpanel#322]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Description

A lot of applications run in the background and show their icons in the WingPanel to let you know that something is running.

![Screenshot from 2020-05-25 23 21 12](https://user-images.githubusercontent.com/18045387/82844494-0364f680-9ee1-11ea-8121-8dc0cce8d82f.png)

In the above image you can see (Chrome, Skype, TeamViewer and Microsoft Teams) have their icons.

Well WingPanel uses only black/white colors. However the applications in the image above <b>do not follow this concept</b>.

## Solution

I guess we need to override these icons with only black/white icons correspond to each application. What I purpose is to have some ready-to-use icons (black/white) for popular applications and when any of these applications run we override the icon with the corresponding one.

**Existing work**

I have no prior experience with Linux or Vala development. But I guess this might be done like:
<ul>
<li>First we need to prepare the icons for the popular applications</li>
<li>We need to store these icons and their paths in something like a ```JSON``` file to check</li>
</ul>

```
{
  "chrome": "icons/chrome.png"
}
```

<ul>
<li>When any application tries to register its overlyIcon, We check this file</li>
<li>If the application exists in the list, We override its icon. Otherwise we simply show its default icon</li>
<li>I'm pretty sure we should start some where near: <a href="https://github.com/elementary/wingpanel/blob/a106951a0e6959424b1a87a49118cd75f7945df8/lib/Widgets/OverlayIcon.vala#L20">https://github.com/elementary/wingpanel/blob/a106951a0e6959424b1a87a49118cd75f7945df8/lib/Widgets/OverlayIcon.vala#L20</a> </li>
</ul>

I know this approach will not cover all applications. But at least it's better than not handle them at all.

**Comment by danrabbit** [comment]
Sorry, I'm going to close this as "Out of scope". We don't support app indicators in elementary OS. You'll have to file this issue against whatever extension you've installed to support this API
