### ISSUE TITLE
Would love to have a "Large Type" option similar to Alfred

### ISSUE THREAD

**Issue by feoh** [elementary/wingpanel#337]
## Prerequisites
- [ X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

As a visually disabled user I often want to be able to select some text and display it in very large type on the screen.

![Example from Alfred on OSX](https://user-images.githubusercontent.com/330070/87744289-18f7ed80-c7b9-11ea-8c19-51f11402484f.png)

**Describe the solution you'd like**

For example, I select a phone number in an email, hit the app launcher hotkey, choose the "Large Text" action and step away from the screen to actually make the phone call.

**Existing work**

Alfred on OSX has this feature, and due to the way OSX works it integrates anywhere you can select text or a text blob.

For instance, in the Contacts app, you can select a phone number, hit the Alfred hot key, and see it in very large text in the center of the screen.

Here is the description of this feature from the [Alfred Site](https://www.alfredapp.com/help/features/large-type/)
**Describe alternatives you've considered**

Having this accessible from the app launcher hot key seems like a natural fit given that the launcher already has similar features like calculation mode for numbers, but I'm not married to that. Anything that would integrate with as many apps as possible given Linux/Gnome's architectural limitations (e.g. there's no AppleEvents/Open Scripting Architecture in Gnome that I know of).

**Additional context**

**Comment by feoh** [comment]
Wrong project :( I think I wanted appmenu.

**Comment by janxkoci** [comment]
FYI this can be done with Kupfer, which is available from the default repos..
