### ISSUE TITLE
Files doesn't come to the foreground if already open, when open through the launcher

### ISSUE THREAD

**Issue by inad9300** [elementary/wingpanel#35]
Say you have Files open. Then you open the browser and maximize it. You then go to the launcher and open Files again. It will open a new tab in the home directory, but it will not bring the window to the foreground.

This is most certainly a Files problem, as oppose to a problem with wingpanel's launcher, but I didn't know where else to report it.

**Comment by danrabbit** [comment]
It seems like this has been fixed somewhere along the line :)
