### ISSUE TITLE
Wingpanel unusable from guest session

### ISSUE THREAD

**Issue by inad9300** [elementary/wingpanel#355]
## Description
When logging in to elementary OS as a guest, attempting to interact with Wingpanel kills it. It simply goes away and never returns, making the OS unusable.

It is rather embarrassing, I must say, to have to justify to your friends and colleagues your choice of a broken OS. Unfortunately, this experience is similar whichever direction you look within the Linux sphere.

## Platform information
- OS: elementary OS 5.1.7 Hera
- Device: Microsoft's Surface Pro 3

**Comment by davidmhewitt** [comment]
Can you confirm whether it's only opening the applications menu that crashes wingpanel? Do the other indicators (network, bluetooth, power, etc...) work if you use those first?

If so, this is probably a duplicate of:
https://github.com/elementary/applications-menu/issues/393

**Comment by inad9300** [comment]
Indeed, it seems to be only the applications menu that breaks it. Sorry for the noise.
