### ISSUE TITLE
Crash when open Application list

### ISSUE THREAD

**Issue by BellemareMederic** [elementary/wingpanel#357]
## What Happened
Sometime when i try to open the Application list, wingpanel just disapear of the screen and i can get it back with Terminal wingpanel but cannot run it in background process =|.
![image](https://user-images.githubusercontent.com/6710664/97013606-37d3f180-1517-11eb-8ac6-bbc055524b5f.png)

## Expected Behavior
Just open the application list and let the wingpanel app running ^_^

## Steps to Reproduce
1.Login in a session
2.Open google-chrome
3.Open Application tab on wingpanel to lautch application.
4.Pouff Wingpanel crash

### Logs
Oct 23 09:54:00 mederic-msi kernel: [ 1070.621344] wingpanel[9830]: segfault at 48 ip 00005625ed44f8e3 sp 00007ffc25d2eff0 error 4 in wingpanel[5625ed441000+18000]
Oct 23 09:54:00 mederic-msi gnome-session[9492]: gnome-session-binary[9492]: WARNING: Application 'io.elementary.wingpanel.desktop' killed by signal 11
Oct 23 09:54:00 mederic-msi gnome-session-binary[9492]: WARNING: Application 'io.elementary.wingpanel.desktop' killed by signal 11
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.window » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/window/29360131
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.window » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/window/29360131
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.window » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/window/29360131
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.window » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/window/29360131
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.window » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/window/29360131
Oct 23 09:54:00 mederic-msi gala[9808]: Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.view » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/application/686748884
Oct 23 09:54:00 mederic-msi gala[9808]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: L'interface « org.ayatana.bamf.application » n'existe pas pour l'objet à l'emplacement /org/ayatana/bamf/application/686748884
Oct 23 09:54:02 mederic-msi plank.desktop[9831]: #033[90m[main 2020-10-23T13:54:02.521Z]#033[0m update#setState checking for updates
Oct 23 09:54:02 mederic-msi plank.desktop[9831]: #033[90m[main 2020-10-23T13:54:02.711Z]#033[0m update#setState idle
Oct 23 09:54:05 mederic-msi nm-applet[9931]: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Oct 23 09:54:05 mederic-msi nm-applet[9931]: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Oct 23 09:54:05 mederic-msi nm-applet[9931]: Can't set a parent on widget which has a parent
Oct 23 09:54:05 mederic-msi nm-applet[9931]: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Oct 23 09:54:05 mederic-msi nm-applet[9931]: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
Oct 23 09:54:05 mederic-msi nm-applet[9931]: Can't set a parent on widget which has a parent
Oct 23 09:54:06 mederic-msi gala[9808]: Error in minimize accounting.

## Platform Information
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera
kernel : 4.15.0-122-generic

**Comment by tintou** [comment]
Salut Médéric,
Pour en savoir plus l'idéal serait d'avoir les informations de debug, pour ce faire voici les étapes:

1. Éditer (ou créer) `/etc/apt/sources.list.d/ddebs.list`:
```
deb http://ddebs.ubuntu.com bionic main restricted universe multiverse
deb http://ddebs.ubuntu.com bionic-updates main restricted universe multiverse
deb http://ddebs.ubuntu.com bionic-proposed main restricted universe multiverse
```

2. Éditer `/etc/apt/sources.list.d/elementary.list` et ajouter `main/debug`
```
deb http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic main main/debug
deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic main
```

3. Installer les clés de sécurité du repo de débogage `sudo apt install ubuntu-dbgsym-keyring`

4. Installer GDB et les paquets de débogage: `sudo apt update && sudo apt install wingpanel-dbg libglib2.0-0-dbgsym libgtk-3-0-dbgsym`

5. Lancer `gdb wingpanel` puis `run` attendre le crash puis entrer `bt`

6. Copier la sortie ici

**Comment by BellemareMederic** [comment]
Je ne sais pas si cela va fonctionner car il crash quand il est gérer par gnome-session. quand je le fais rouler avec mon terminal il ne crash jamais :| est t'il possible de debugger gnome-session a l'ouverture ?

**Comment by selwynorren** [comment]
I seem to be having the same issue. Every time after boot/reboot, wingpanel will crash. Fortunately for me it reloads again automatically, but this is consistent with every initial boot, or computer reboot

**Comment by BellemareMederic** [comment]
@selwynorren Samething after boot if my wingpanel crash 2 time i cannot reopen it and i need to reboot :|. But my setup is a mess right now. i try to move all /home directory to an other disk but i think i broke something with symlink XD

**Comment by selwynorren** [comment]
Since my last comment, I started to use the new Daily release for Odin. and initially it never happened, but now recently even in Odin it crashes, however now its random. Previously in Hera it would always be the first time I clocked on Applications after a boot. Now its at random intervals
