### ISSUE TITLE
wingpanel: Indicator menus have incorrect window type

### ISSUE THREAD

**Issue by quequotion** [elementary/wingpanel#36]
It may not an issue for Gala, but all the indicators displayed by wingpanel inherit its window type and class.

I used `sleep 4; xprop` to check on slingshot, ayatana indicators, and the native indicators; they all have:
`_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK`
`WM_CLASS(STRING) = "wingpanel", "Wingpanel"`

Inheriting the class is fine, but I'd prefer if the indicator menus were mapped as _NET_WM_WINDOW_TYPE_MENU. This is useful when running wingpanel under other window managers that use window type to determine decorations.

[Freedesktop's _NET_WM_WINDOW_TYPE specification](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm139870830002400)

**Comment by tintou** [comment]
Indicators are simply plugins of Wingpanel, they do inherit the window type because the window is actually wingpanel. Nothing that we can do here I'm afraid…

**Comment by quequotion** [comment]
Other panels are type DOCK and have menus that are type MENU, such right-click menus in plank.

I think it is possible, but I see the difficulty--wingpanel doesn't distinguish between itself and its components to the window manager; IndicatorEntry has no "type_hint".

**Comment by parnold-x** [comment]
That's because these menus in plank are own windows. Wingpanel uses popovers that are not own windows in gtk+ x11. In wayland they should be owned windows.

**Comment by donadigo** [comment]
That's something to consider doing when porting to Wayland, yes. Popovers have their on windows there while on X11 they can only allocate space that their parent has.

**Comment by quequotion** [comment]
In which case can we reopen? I don't mind if it isn't an immediate priority, but it sounds like changes will have to be made eventually.

**Comment by quequotion** [comment]
Could we use Gtk.PopoverMenu?

I tried just replacing Gtk.Popover with Gtk.PopoverMenu on line 22 of src/Widgets/IndicatorPopover.vala, but it seems that's not enough; compile failed with:
`build/src/Widgets/IndicatorPopover.c:42:17: error: field ‘parent_instance’ has incomplete type`
