### ISSUE TITLE
Wingpanel has no Manpage and I'm a total noob

### ISSUE THREAD

**Issue by ChristopherTheBoss** [elementary/wingpanel#361]
## Problem

I'm trying to shape up an OS for my Aunt as a Christmas present.

I really like a lot of what eOS does, but some things I would like to change as a matter of personal preference. For example, I would like to change for format of the clock to just indicate the day. I dislike military time, so I've changed that already. Going beyond this has proven impossible. Back when eOS was first conceived you use a custom UNIX time formatting string in a parameter accessible by dconf editor. No longer is this possible.
Here's the deal. I'm going to spell this out for you. If I understand what a UNIX time string looks like and how to format one myself, there should be ~~a place for me to put one in a text file.~~ a variable I can modify to impact the UI. I do not care if don't have a setting exposed for unenlightened user to accidentally stumble upon and mess up your perfect environment. I've looked at the source code of this program and gone through the [Granite Library](https://github.com/elementary/granite/blob/master/po/en_GB.po) that contains a list of default time formats: now I have no idea how many steps are involved in setting up the compilation chain from the Granite Library to the DateTime Indicator to Wingpanel. I did everything I could to comprehend the steps I'd need to take in order to get this working without wasting YOUR time asking for help. So I decided to look up the Wingpanel manpage. There isn't one. Wingpanel is therefore Undocumented in the traditional UNIX sense. In order find out what this program was called I needed to do some Googling. That's tight integration! I looked up elementary OS "bar" because I know of a program called lemonbar that is tempting me right now. I considered switching to it but I realized I'd be sacrificing the beautifully integrated System Indicators.

In the stack exchange post detailing [how to get a custom date format](https://elementaryos.stackexchange.com/questions/1943/can-i-change-the-date-format-in-the-panel) with first reply being a bit old, I continued to the second reply.

> "The answer above does not work. But the following method will work for both the date and time formats."

Of course this threw me off. They link an issue with wingpanel date indicator that is resolved. [The solution was](https://github.com/elementary/wingpanel-indicator-datetime/issues/57) to add the specific date format the person who had opened issue wanted... and remove method of adding a custom date format in the locale datetime-indicator.mo ... This ~~is insidious.~~ makes me sad. I decompiled the exact .mo into a .po as per the instructions, only to find the same filename had either been repurposed to solely affect the calendar part of the indicator or had the main formatting string moved elsewhere (I'm a noob I didn't look for it in the filesystem)

You are nothing without us, your users. We demand the freedom to have access to the same powerful logic that was leveraged to create the environment, without the need to unravel the whole project and spin it back together.

If I wanted a computer that stopped me from going too far into UNIX I would buy an Apple Mac and use OS X.

If I was happy with the incoherent mess that is Windows, I wouldn't be at your doorstep, begging for user interface design that keeps the UNIX philosophy.

## Proposal

This is the source code that you use to format the date in the Wingpanel DateTime Indicator, paraphrased

`GLib.DateTime? current_time = new GLib.DateTime.now_local (); `
`string time_format = Granite.DateTime.get_default_time_format (time_manager.is_12h, clock_show_seconds);`
`current_time.format (time_format);`

Granite.DateTime checks some settings and references [a file that looks like this](https://github.com/elementary/granite/blob/master/po/en_GB.po).

If the desktop environment has a pool of variables similar to that of a shell, I would like the time format to be exposed in these variables so that I can programmatically set a string to reflect the Day and which part of that day it is.

Right now I would have it display:
### Monday Night.

I want this and I know I want this. I'm not mistaken in wanting this.

However, the idea is not yet complete. I recognize that keeping a more precise understanding of the time is important for certain productivity. I am a runner. I have done track workouts. I have run 3 miles in 15 minutes. I kept very close timing during those sessions. Most of the time I run I don't care about specifics.

I want people to engage with clock and keeping it vaguely beautiful at first is a way to encourage them to explore it.

Having the day and part of the day is tasteful, and users would assume there is deeper functionality.

## Prior Art

I like the clock that you have centered in the bar. It is where it would be in a school classroom or a regular room. My Windows clock sits awkwardly in the bottom left hand corner and I rarely look at it.

## Conclusion

I'll probably program this myself, but writing it all out was therapeutic. Wingpanel is modular enough that I can change the DateTime

**Comment by danrabbit** [comment]
I am actively disinterested in helping someone who thinks "you are nothing without us" is an appropriate thing to say. I would be happy to refund your purchase if you want to send an email to billing @ elementary.io

**Comment by cassidyjames** [comment]
I concur, and there's not really anything actionable here. It sounds like @ChristopherTheBoss wants a specific thing for a specific use case, and has the ability to poke at the code to implement it. For the record, the Date & Time indicator is located at https://github.com/elementary/wingpanel-indicator-datetime, not in this repository. You probably want to look here: https://github.com/elementary/wingpanel-indicator-datetime/blob/30656a5af9c7ba3a5430c3f5e3dea719f65fd88d/src/Widgets/PanelLabel.vala#L58-L70
