### ISSUE TITLE
Some indicators are cut a bit when clicking on indicators

### ISSUE THREAD

**Issue by Loreno10** [elementary/wingpanel#362]
## What Happened

When clicking some indicator, the "Bluetooth" and "Notifications" indicators are cut from the bottom a little. You can observe it here:

![blutooth_notifications_indicators_issue](https://user-images.githubusercontent.com/10273406/103179592-f3a1fc00-488d-11eb-9874-809a89b870bc.gif)

## Expected Behavior

The icons should not get cut when I click an indicator.

## Steps to Reproduce

The issue happens only when there isn't any maximized window. I noticed that it is sometimes not reproducible when there are ANY windows on the screen (even not maximized). 

Click any indicator on the wingpanel.

## Platform Information
eOS 5.1.7

**Comment by danrabbit** [comment]
I'm not able to reproduce this issue on 6.0 daily, so this may have been solved. Needs someone to reproduce there

**Comment by fs3o5** [comment]
I can only reproduce it in 5.1.7 but not in 6.0.

**Comment by danrabbit** [comment]
Since we have two people saying they can't reproduce in 6.0 I'm going to close as "incomplete". If someone can reproduce it in 6.0, please comment and then we can reopen :)
