### ISSUE TITLE
Using Wingpanel-3.0 with the indicators

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel#363]
## What Happened
Currently all the indicators in elementary have `dependency('wingpanel-2.0')` (and maybe a version constraint added for certain changes). When using wingpanel master it fails to configure with
```
Run-time dependency wingpanel-2.0 found: NO (tried pkgconfig)
  
meson.build:23:0: ERROR: Dependency "wingpanel-2.0" not found, tried pkgconfig
  
 A full log can be found at /build/source/build/meson-logs/meson-log.txt
```

how are you even QA'ing the indicators for Odin if it's impossible to build them?
Currently in the process of evaluating Odin for NixOS but I have to either revert the version bump or symlink it for compat.

**Comment by decathorpe** [comment]
I have the same problem in Fedora nightly builds. I need to keep an old snapshot of wingpanel around, because without it, none of the indicators build.

**Comment by worldofpeace** [comment]
I think they're being updated to the new `wingpanel`, so I will close this

**Comment by decathorpe** [comment]
Yep, all indicators should be updated to use wingpanel (without version qualifier), which should also make future transitions like this easier.
