### ISSUE TITLE
Wingpanel gets not automatically restarted if killed twice

### ISSUE THREAD

**Issue by etkaar** [elementary/wingpanel#364]
Usually wingpanel gets automatically restarted if one would enter following command:

`killall wingpanel`

However, if you then kill wingpanel again, it is not going to be restarted again.

Is that a bug or intended behaviour?

**Comment by meisenzahl** [comment]
"If wingpanel is stopped/killed twice within a minute, it will stop automatically restarting, ..."

Reference: https://elementary.io/de/docs/code/os-dev#elementary-sdk
