### ISSUE TITLE
App indicators appear in between system indicators

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/wingpanel#366]
## What Happened

App indicators appear in between system indicators.
![image](https://user-images.githubusercontent.com/31680656/105627961-ecfaaa80-5e74-11eb-9a98-b5d3cf3f0c6b.png)

## Expected Behavior

Although app indicators aren't supported, there should be at least some check to ensure that system indicators appear on the far right with any other custom indicator appearing to the left of system indicators.

## Steps to Reproduce

1. Turn on night light.
2. Install random app indicator ([wingpanel-indicator-template](github.com/pongloongyeat/wingpanel-indicator-template) for example).

**Comment by danrabbit** [comment]
There's no way to ensure this since as far as the panel is concerned there's no such distinction between types of indicators. There is only indicators

**Comment by davidmhewitt** [comment]
Sounds like we just need to add the nightlight indicator here, along with any other new ones we've missed:
https://github.com/elementary/wingpanel/blob/ef0908ea25f541f7e4944819e473f96d972ef048/src/Services/IndicatorSorter.vala#L33-L45

**Comment by pongloongyeat** [comment]
Huh never knew there was a printer indicator and I do wonder what the sync indicator is :open_mouth:

Here's the list of un-added indicators for your convenience:

- wingpanel-indicator-datetime
- wingpanel-indicator-nightlight
- wingpanel-indicator-privacy
- wingpanel-indicator-a11y

**Comment by davidmhewitt** [comment]
This is now resolved, thanks again @pongloongyeat !
