### ISSUE TITLE
Configurable order of indicators

### ISSUE THREAD

**Issue by smelnikov** [elementary/wingpanel#38]
Current sorting algorithm of indicators little bit confusing for users (system indicators fixed, user indicators sorted alphabetically) .
Can we get some settings for set manually order of all indicators on panel?!

**Comment by cassidyjames** [comment]
Since we don't encourage app indicators in the first place, I'm not in favor of adding fiddly settings to arbitrarily move things around. I could be convinced of better sorting algorithm or something, but the exact order should be consistent.
