### ISSUE TITLE
Wingpanel font colour does not change according to background on restart

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/wingpanel#385]
## What Happened

Filing as separate of #292 since that issue describes transparency when apps are maximised.

When changing backgrounds to a _lighter_ background, the font colour in Wingpanel should turn black like so

![Screenshot from 2021-03-13 05-44-44](https://user-images.githubusercontent.com/31680656/111002335-37ea6600-83c0-11eb-9ef0-acab44dae76b.png)

But after a restart, Wingpanel doesn't seem to set the correct font colour.

![Screenshot from 2021-03-13 05-47-07](https://user-images.githubusercontent.com/31680656/111002376-4a649f80-83c0-11eb-9131-c144cafc623e.png)

## Expected Behavior

It should set the correct font colour.

## Steps to Reproduce

1. Use the same background as in the image above.
2. Log out.
3. Log in.
4. See Wingpanel font colour.

## Platform Information
Wingpanel daily

**Comment by pongloongyeat** [comment]
I've also just realised that the font colour only changes on my laptop but not my desktop

**Comment by davidmhewitt** [comment]
Sounds like this might be https://github.com/elementary/gala/issues/613

**Comment by pongloongyeat** [comment]
@davidmhewitt This does not fix itself when changing backgrounds after logging in.

**Comment by pongloongyeat** [comment]
Closing this due to a duplicate #358
