### ISSUE TITLE
wingpanel-interface/meson.build:29:1: ERROR: Problem encountered: No supported mutter library found!

### ISSUE THREAD

**Issue by klascano** [elementary/wingpanel#399]
## What Happened
Can't compile winpanel

## Expected Behavior
wingpanel-interface/meson.build:29:1: ERROR: Problem encountered: No supported mutter library found!

## Steps to Reproduce
All dependencies previously installed

1. $ meson build --prefix=/usr

### Logs
The Meson build system
Version: 0.55.1
Source dir: /home/klascano/BESIX/GIT/wingpanel-master
Build dir: /home/klascano/BESIX/GIT/wingpanel-master/build
Build type: native build
Project name: io.elementary.wingpanel
Project version: 3.0.0
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
Vala compiler for the host machine: valac (valac 0.40.25)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency glib-2.0 found: YES 2.56.4
Run-time dependency gio-2.0 found: YES 2.56.4
Run-time dependency gio-unix-2.0 found: YES 2.56.4
Run-time dependency gmodule-2.0 found: YES 2.56.4
Run-time dependency gdk-x11-3.0 found: YES 3.22.30
Run-time dependency gtk+-3.0 found: YES 3.22.30
Run-time dependency gee-0.8 found: YES 0.20.2
Run-time dependency granite found: YES 5.5.0
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Library config found: YES
Configuring config.h using configuration
Found CMake: /usr/bin/cmake (3.10.2)
Run-time dependency libmutter-6 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-7 found: NO (tried pkgconfig and cmake)

wingpanel-interface/meson.build:29:1: ERROR: Problem encountered: No supported mutter library found!

A full log can be found at /home/klascano/BESIX/GIT/wingpanel-master/build/meson-logs/meson-log.txt

## Platform Information
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera

**Comment by danrabbit** [comment]
Thanks for filing a report! Wingpanel now requires Mutter >= 3.36. It is no longer possible to build it for OS 5.x. If you want to build wingpanel from source you'll need to use OS 6
