### ISSUE TITLE
User "Nobody" on power menu

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/wingpanel#40]
Hi.

Last week or so, whenever I turn my computer on, while having Guest user disabled and removed from Pantheon Greeter, there is another user in my power menu - "Nobody".
I've never had this issue before, luckily I can remove it following these steps:
Switchboard > User Accounts > Unlock > Enable Guest > Disable Guest > Lock > Logout > Login

Screenshot: [https://screencloud.net/v/ntXds](https://screencloud.net/v/ntXds)

Info:
elementary OS 0.4.1 Loki (64bit) only Stable PPA
Linux 4.4.0-81-generic
GTK+ 3.18.9

**Comment by WebShapedBiz** [comment]
Update on this (I hope someone is reading)
I spent last few days trying to find out what is triggering user Nobody to appear since it's never there on startup. For the second time now, it appeared during `apt dis-upgrade` process.
No, I'm not kidding. I went crazy over this, opening power menu after running each application for days now. When it happened first time I thought maybe it was coincidental but today it happened for the second time on `apt dist-upgrade` and never after some other application.

**Comment by WebShapedBiz** [comment]
Sorry, I've closed this issue by mistake

**Comment by vjr** [comment]
Instead of `apt dist-upgrade` can you try `apt full-upgrade` and see if it avoids the problem? I usually update my system from terminal using `sudo apt full-upgrade` command after `sudo apt update`.

**Comment by WebShapedBiz** [comment]
Thank you for your answer but I'm not trying to find a way around. I'm reporting a issue/bug that was not previously there.

**Comment by davidmhewitt** [comment]
I'm going to close this issue as there is nothing that can be done about it in `wingpanel`. I see you have raised the same issue in the `wingpanel-indicator-session` repository, so the issue can be tracked there:
https://github.com/elementary/wingpanel-indicator-session/issues/23

Thank you for reporting this and feel free to add any extra information there
