### ISSUE TITLE
Screen Rotation Lock should be accessible from wingpanel.

### ISSUE THREAD

**Issue by seltzered** [elementary/wingpanel#401]
## Problem
A typical use case for a tablet is to use it in portrait mode. A user may want to 'lock' the screen in this mode (particularly when reading when lying down on a couch). Right now elementary wingpanel (tried in elementaryos 6 beta 2) doesn't appear to have an option to lock screen rotation easily, so instead a user has to open the settings, then go to display options, then click the option to lock screen rotation. This feels like more actions than on most direct input devices (phones, ipads, etc.) 

## Proposal
Consider adding a screen rotation lock button to wingpanel if device is capable of rotation. Can be a on-off switch (akin to say wifi/bluetooth enable buttons). Screen rotation lock should be in sync with state as set in the settings app.

## Prior Art
Ubuntu (as of 21.04 at least) does have a screen rotation lock button that contextually appears in it's top right menu (i.e. the battery/sound/wifi button) when in portrait mode. 
In actual use ubuntu's implementation feels buggy and inconsistent though, and doesn't provide a user option around 'automatic' screen rotation in their settings menu (i.e. I have no idea if setting an orientation to portrait in settings means it will stay that way)

**Comment by danirabbit** [comment]
Closed in https://github.com/elementary/quick-settings/pull/14
