### ISSUE TITLE
Wingpanel indicators opening on hover

### ISSUE THREAD

**Issue by andrea-scape** [elementary/wingpanel#402]
Hi, i'm using elementary OS 5.1.7 and when i click on an indicator the menu for that idicator closes if i move the cursor on another idicator. es if i click on the wifi indicator and move my mouse slightly automatically the sound or notification menu appears.

I don't expect this behavior when i click on something. For example in windows if you click on a system tray icon and you move your mouse the menu you opened remains open until you click somewhere else.

Is this "corrected" on elementary OS 6?

Thanks in advance

**Comment by danrabbit** [comment]
This is intentional behavior and it's called "scrubbing". You'll notice the same behavior on menubars. This feature makes it easier to quickly move between menus in the case of a mis-click

Closing as "Design conflict" since this is an intentional feature
