### ISSUE TITLE
Tray icons support that everyone waits from Elementary devs.

### ISSUE THREAD

**Issue by AzeAstro** [elementary/wingpanel#406]
# Main
Tray icons doesn't work on Elementary 6. I tried all working methods for Elementary 5.1 but none of them worked.  

## Proposal
Add native tray icon support to all Elementary versions(at least, to 6).

## Screenshot
Steam and Discord tray icon is activated but none of them is showing up on wingpanel.
![](https://i.ibb.co/mc5WBX7/Screenshot-from-2021-08-15-20-35-18.png)

For more, you may check this question in Elementary's stack exchange: https://elementaryos.stackexchange.com/questions/28500/tray-icon-support-in-elementary-6-odin-single-click-in-file-manager

**Comment by cassidyjames** [comment]
This has been answered at length elsewhere. https://github.com/elementary/wingpanel/discussions/360
