### ISSUE TITLE
Wingpanel has top gap when apps are snapped to left-half/right-half

### ISSUE THREAD

**Issue by aral** [elementary/wingpanel#408]
## What Happened
  
![Screenshot from 2021-08-19 09-39-23@2x](https://user-images.githubusercontent.com/41798/130039099-03a5a6f8-c97f-48f8-84db-dba88185d459.png)

![Screenshot from 2021-08-19 09-42-19@2x](https://user-images.githubusercontent.com/41798/130039119-7884698e-15f0-4d26-abc0-09df5098bd36.png)

Wingpanel left a gap at the top of the screen in its opaque black view when an app was snapped to the left/right side of the screen.

## Expected Behavior

There should be no gap.

## Steps to Reproduce

This doesn’t happen all the time. To reproduce, maximize an app  or snap it to an edge.

### Logs

n/a

## Platform Information

From neofetch: 

```
OS: elementary OS 6 Odin x86_64 
Host: LabTop Mk IV 
Kernel: 5.11.0-25-generic 
Uptime: 13 hours, 7 mins 
Packages: 2000 (dpkg), 28 (flatpak) 
Shell: fish 3.3.1 
Resolution: 1920x1080, 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 2167MiB / 15875MiB 
```

PS. Template says screenshot information at System Settings -> About but:

![Screenshot from 2021-08-19 09-48-05@2x](https://user-images.githubusercontent.com/41798/130038935-ccc2a5b8-480c-42a4-8820-b66d076583d7.png)

**Comment by cassidyjames** [comment]
>PS. Template says screenshot information at System Settings -> About but:

Fixed :) https://github.com/elementary/.github/commit/004ae11c093497c2a34cedb2a21a232e56532db9

**Comment by aral** [comment]
@cassidyjames Merci :)
