### ISSUE TITLE
Commandline option to hide/show Wingpanel

### ISSUE THREAD

**Issue by aral** [elementary/wingpanel#424]
### Problem

__Use case:__ I want to automate screenshots for my app and for that I want to show/hide Wingpanel.

### Proposal

Having the ability to show/hide the system bar using a command-line interface would enable folks who need this functionality for advanced purposes.

Killing the Wingpanel process does not achieve this as it is respawned.

Previously you could remove it from being respawned but now you can’t do that either.

Less clean alternative: document how the Wingpanel process can be killed dead (really dead) :)

### Prior Art (Optional)

A lot of tools have a command-line interfaces for advanced functionality that is useful in scripted scenarios.

**Comment by danrabbit** [comment]
Can you clarify how the panel is related to your app screenshots? Curious about that
