### ISSUE TITLE
Blacked effect doesn't work properly with two screens

### ISSUE THREAD

**Issue by inad9300** [elementary/wingpanel#43]
I have my laptop plugged to an external monitor via VGA. Wingpanel (placed on my laptop's screen) _only_ dims out when I maximize a window on my external monitor. The desired behavior in my view would be to dim it out _only_ when a window is maximize where wingpanel is.

![window-maximized-on-laptop-monitor](https://user-images.githubusercontent.com/3440331/28377425-fe30817a-6cac-11e7-8d3c-57f749b5501e.png)

![window-maximized-on-external-monitor](https://user-images.githubusercontent.com/3440331/28377426-fe344922-6cac-11e7-941c-005eff4efdd8.png)

Notice that it does not matter at all whether a window is maximized on the laptop's screen or not.

**Comment by taehyounpark** [comment]
I have the same issue with nvidia graphics driver installed (in both dGPU & iGPU modes). Wingpanel behaves correctly with nouveau driver.

**Comment by cassidyjames** [comment]
I think this logic is handled by Gala, so I've reported this over at https://github.com/elementary/gala/issues/165
