### ISSUE TITLE
Feature: Move Restart option from the Shutdown sub-menu

### ISSUE THREAD

**Issue by joeljose350** [elementary/wingpanel#432]
### Problem

The option to Restart the computer in the Shutdown sub-menu of the Power widget in the Wingpanel can be hard to find as most people would think that it would appear as an option in the main menu.

### Proposal

Moving the Restart option to the Power widget in the Wingpanel would make it easier to find. A modal to ask the user if they want to continue with the Restart process will be beneficial, in my opinion.

![image](https://user-images.githubusercontent.com/53969297/149746518-5c8db9dd-bcbc-4f71-855a-3ebb71aaf26c.png)

### Prior Art (Optional)

This is how the feature is implemented in Pop!_OS 21.10.

![image](https://user-images.githubusercontent.com/53969297/149746992-a1165fbb-42ed-468b-8fae-728c70c17988.png)

![image](https://user-images.githubusercontent.com/53969297/149747087-0f9b9732-bc96-4e41-9962-96bae898080d.png)

**Comment by cassidyjames** [comment]
Eh, in your example, it's just as hidden and actually requires _more_ actions to restart:

1. Click the indicator
2. Click `Power Off / Log Out` to expand the hidden actions
3. Click `Restart…`
4. Click `Restart` in the dialog

Whereas in elementary OS, it's:

1. Click the indicator
2. Click `Shut Down…`
3. Click `Restart`

Considering we don't frequently recommend or require restarting the OS—and when we do (e.g. with a firmware update or a kernel update), we prompt in related app which already directly opens the restart dialog—I think the current level of priority given to restarting is appropriate.
