### ISSUE TITLE
Additional indicators for microphone / camera / location use

### ISSUE THREAD

**Issue by ovz93br43v7** [elementary/wingpanel#439]
### Problem

I think it would be very useful to see whether the microphone / camera / location is accessed by any app as an indicator.

### Proposal

Extend the indicators so that a camera / microphone / location symbol is shown when any app is accessing the camera / microphone / location.

### Prior Art (Optional)

On Android 12 there is an tiny green bubble in the top right corner and when you pull down the top menu a green microphone / camera / location symbol is shown. (--> https://therecord.media/wp-content/uploads/2021/05/camera-indicators.png)

**Comment by cassidyjames** [comment]
Microphoone access is already implemented in the [sound indicator](https://github.com/elementary/wingpanel-indicator-sound); the other proposals are already covered by the [privacy indicator](https://github.com/elementary/wingpanel-indicator-privacy) which has not yet been included in elementary OS, but could be in the future.
