### ISSUE TITLE
Transparency under text & icons has been lost

### ISSUE THREAD

**Issue by FunkySalamander** [elementary/wingpanel#496]
### What Happened?

A recent update as of this week (2023-08-20) has caused the top panel to lose transparency under areas with text & icons. Instead there are grey blocks.

### Steps to Reproduce

Boot
Login

### Expected Behavior

Transparent area as is displayed between grey blocks should continue through where the grey blocks have appeared.
![2023-08-25_Top_of_Screen](https://github.com/elementary/wingpanel/assets/125952784/27efd820-7ac9-4da5-bcf2-4ec257134499)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by zeebok** [comment]
Are you using any kind of modified theme or tweaking application?

**Comment by FunkySalamander** [comment]
> Are you using any kind of modified theme or tweaking application?

Nope, I think my Network icon is dead because I tweaked /etc/network/interfaces for a network bond.

**Comment by danirabbit** [comment]
The window decorations here are definitely not the elementary stylesheet

**Comment by FunkySalamander** [comment]
I have KDE installed but AFAIK it's not affecting anything.

Where would I look to see about setting that back to normal?

**Comment by danirabbit** [comment]
You're using an entirely different unsupported system stylesheet. You can reset default settings in System Settings → System → "Restore Default Settings"

Closing since this is a configuration issue

**Comment by FunkySalamander** [comment]
That fixed it, tyvm.
