### ISSUE TITLE
The WiFi indicator keeps moving over to the left side next to the calendar and time.

### ISSUE THREAD

**Issue by Imauny** [elementary/wingpanel#502]
### What Happened?

The WiFi indicator keeps moving over to the left side next to the calendar and time. On reboot that issue is fixed and then it happens again overtime.

### Steps to Reproduce

Looked at the WiFi indicator and moved over a little to the left and left a wide gap.

### Expected Behavior

it should be close to the Bluetooth indicator, but there is a big gap.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Dual-Core Intel® Core(TM) i3-7100U CPU @ 2.40GHz
Intel® HD Graphics 620

**Comment by stsdc** [comment]
Confirm. For me its keyboard layout indicator, or sound indicator on notebook.

**Comment by unamlosito** [comment]
Same thing here, happens with volume indicator, keyboard indicator and also with 3rd party tray icons too
![Cattura da 2023-09-12 15 40 20](https://github.com/elementary/wingpanel/assets/75470977/60248625-36b2-4eb8-88d9-b77fa3d6e0dc)
