### ISSUE TITLE
wingpanel icon on Dock

### ISSUE THREAD

**Issue by megatux** [elementary/wingpanel#52]
If anything helps I think this started appearing after some debug with the GTK inspector and an applet (sound switcher indicator)
![captura realizada el 2017-09-04 10 37 01](https://user-images.githubusercontent.com/850020/30028878-3c16d668-915d-11e7-8502-f99bd4f7e495.png)

**Comment by cassidyjames** [comment]
@megatux does this issue persist after rebooting? Inspecting (which draws a window as a child of WingPanel) may have put things into a weird state, but it should go away after a reboot.

**Comment by megatux** [comment]
@cassidyjames after reboot the icon persist in the dock

**Comment by megatux** [comment]
Forgot to mention, I fixed it by doing Menu, remove from dock :relaxed:

**Comment by BrusAndr** [comment]
I ran into a similar problem. When I try to connect to a hidden network, the Wingpanel icon remains in the dock. Buttons "remove from dock" and "close" don't work.

![2017-10-07 23 24 22](https://user-images.githubusercontent.com/29145756/31311603-7c4bf2ca-abb8-11e7-88bb-8b0348eea7c3.png)
![2017-10-07 23 24 54](https://user-images.githubusercontent.com/29145756/31311626-e2919c2e-abb8-11e7-8f8a-eb9c447b8022.png)
![2017-10-07 23 25 26](https://user-images.githubusercontent.com/29145756/31311631-f6b38c94-abb8-11e7-8951-246b85803ce6.png)

**Comment by cassidyjames** [comment]
I think both of these are technically by design since those child windows need an icon, and Plank is helpfully adding the icon for them. Even so, I think this would be a bug in Plank, not the panel itself.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Looks like the issue's still valid.
I don't know exactly how it can be reproduced that all of a sudden there's a wingpanel icon in the dock. But it's a bit crazy when I click on the Wingpanel icon in Plank and suddenly can hide the Wingpanel bar completely. Or isn't this the same issue?

**Comment by isneezy** [comment]
I've got the very same problem. At first i thought it was the upgrade from 5.0 to 5.1 but days ago i installed from scratch and few hours later the icon went back and Restart doesn't help at all.

![Screenshot from 2020-02-05 21-02-00](https://user-images.githubusercontent.com/8999039/73873733-cfdf5d00-485a-11ea-967d-10ff2a0afe70.png)

**Comment by ryonakano** [comment]
Hid @isneezy, did you try to connect to a hidden wireless network from the network indicator and face this issue?

**Comment by ryonakano** [comment]
Just noting this issue is a duplicate of elementary/wingpanel-indicator-network#129 and should be fixed in elementary/wingpanel-indicator-network#132 but still reproducible in the latest Hera because a new version of Wingpanel Network Indicator has not been released yet.

**Comment by isneezy** [comment]
@ryonakano I wasn't sure about trying  to connect to hidden network today, I normally use it a lot because most of the times EOs takes to long to find my WiFi. The thing is i did a restart after seeing you comment and i noticed that the icon is gone but after trying to connect to a hidden network it comes back.
Thanks for the fix, i hope it doesn't take so long to  elementary/wingpanel-indicator-network#132  be released

**Comment by ryonakano** [comment]
[A new version of Wingpanel Network Indicator](https://github.com/elementary/wingpanel-indicator-network/releases/tag/2.2.3) was released. This issue should resolve in a few days. Check the system updates :)
