### ISSUE TITLE
does not follow accent color in X session

### ISSUE THREAD

**Issue by teamcons** [elementary/wingpanel#530]
### What Happened?

When starting the EOS 8 Preview (Latest: 11 May), and choosing Banana accent color, the application menu stays with the blue one (search bar outline, app backdrop)

The issue persists even killing wingpanel or starting it manually

### Steps to Reproduce

1. Start live of EOS 8 Preview (11 May)
2. Choose an accent color in the greeter thingy (here, Bananana)
3. Go all the way through it, enjoying the options, like an user would
4. Open application menu

### Expected Behavior

Applied accent colour: Banananana colour on search outline and apps backdrop

I assume both read a different GTK stylesheet (one GTK4 the other GTK3 ?)

Probably the team is already aware or this is too early in the dev process, but in case not, why not try my hand at that contributing thing :)

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Also, this issue doesn't seem to occur in Greeter session:

![greeter](https://github.com/elementary/wingpanel/assets/26003928/f74188b0-cb20-4396-a545-29305e758f4f)

**Comment by danirabbit** [comment]
I can't confirm this issue in a regular session. @ryonakano are you still able to reproduce this?

**Comment by ryonakano** [comment]
Yes, I can still reproduce this on updated Early Access. I'm on X session:

[test-screen0.webm](https://github.com/elementary/wingpanel/assets/26003928/50238813-6878-4ecf-8e9a-b4d50d390d12)

**Comment by ryonakano** [comment]
I can't reproduce this on Wayland

**Comment by zeebok** [comment]
I can confirm the same. X11 wingpanel doesn't use accent color (even after logging out and back in) but I do see it updated in greeter and wayland.
