### ISSUE TITLE
Struts aren't updated on DPI change

### ISSUE THREAD

**Issue by danirabbit** [elementary/wingpanel#540]
### What Happened?

If you change from HiDPI to LoDPI panel struts aren't updated

### Steps to Reproduce

1. Start with HiDPI
2. Maximize a window
3. Change to LoDPI
4. See that there's a gap between the panel and the maximized window

### Expected Behavior

Struts should update on DPI change

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

**Comment by leolost2605** [comment]
Is this on X or on wayland?
