### ISSUE TITLE
Wingpanel changes size when using certain wallpapers

### ISSUE THREAD

**Issue by lenemter** [elementary/wingpanel#552]
### What Happened?

![Screenshot from 2024-07-28 20 26 07](https://github.com/user-attachments/assets/fb0de70e-469c-4e23-971d-1e522c9b39e1)

![Screenshot from 2024-07-28 20 26 24](https://github.com/user-attachments/assets/66889540-feee-4d72-9b0a-2a3010621abc)

### Steps to Reproduce

1. Set [this wallpaper](https://github.com/user-attachments/assets/634398f3-bf5d-4650-8136-c2c439378098)
2. Maximize/unmaximize any window

### Expected Behavior

The panel height stays the same

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by zeebok** [comment]
I do see some kind of shift. I can't tell if it is the panel changing size or the text moving down.
