### ISSUE TITLE
Most indicators missing on Wayland

### ISSUE THREAD

**Issue by 00p513-dev** [elementary/wingpanel#562]
### What Happened?

After upgrading my system, most indicators are missing on the Wayland session, only the calendar remains.

### Steps to Reproduce

1. Upgrade elementary
2. Login to the Wayland session
3. All the indicators are gone

### Expected Behavior

The indicators should be visible, particularly the power related ones

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Intel system with an AMD RX7600 GPU installed

**Comment by 00p513-dev** [comment]
Attached a picture showing the current state of my elementary install

![Screenshot from 2024-08-15 09-17-08](https://github.com/user-attachments/assets/a2899d5e-4ee2-4ac0-bd34-2e75d877daf8)

**Comment by danirabbit** [comment]
I saw this on my StarLite the other day. Seems like it has to do with scaling. The indicators are there, they're just way off screen 😅

**Comment by danirabbit** [comment]
Looks like this was caused by https://github.com/elementary/wingpanel/pull/559

**Comment by 00p513-dev** [comment]
Just tried compiling from git on the commit that solved #559, following instructions in the README.md but this doesn't resolve the issue.

However everything seems OK at 1x scaling, except my eyesight

**Comment by danirabbit** [comment]
@00p513-dev I just proposed a branch with a fix https://github.com/elementary/wingpanel/pull/563

#559 seems to be the branch that caused this issue, it is not the branch that contains the fix

**Comment by 00p513-dev** [comment]
> @00p513-dev I just proposed a branch with a fix #563

Thanks a lot, just compiled on my system and all is good now.

> #559 seems to be the branch that caused this issue, it is not the branch that contains the fix

Apologies, I misread
