### ISSUE TITLE
Top panel workspace scroll

### ISSUE THREAD

**Issue by teamcons** [elementary/wingpanel#582]
### Problem

There is no quick switcher, neither on the top panel or the dock, to navigate immediately between workspaces

The multitasking view allows to change workspace, but requires travelling all the way down, clicking, clicking on desktop

The keyboard allows to change workspace, but it may not always be quickest to do key combos

### Proposal

Scroll on the top panel, on an empty space (no indicator)

back to go to workspace on the right
forth to go to workspace on the left

wrap around if scrolling too far in one direction

### Prior Art (Optional)

This extension in Gnome-Shell does that stuff. Maybe some code can be scavenged if the idea has appeal ?

https://github.com/timbertson/gnome-shell-scroll-workspaces

**Comment by lenemter** [comment]
There is a switch in desktop settings that does exactly what you want ;)

**Comment by lenemter** [comment]
Oops we haven't released that feature yet. Should be available in a couple of days
