### ISSUE TITLE
App Indicators

### ISSUE THREAD

**Issue by Imauny** [elementary/wingpanel#584]
### Problem

Reimpliment Wingpanle indicator.

### Proposal

It would be really nice for you guys to reimplement the Wingpanel app indicator. It would be very useful for seeing notifications from WhatsApp, Telegram, and so on, as well as toggling certain options from those quick-to-reach indicators.

**Comment by stsdc** [comment]
Some explanation on tray icons : https://github.com/elementary/wingpanel/discussions/360

**Comment by Imauny** [comment]
Dear Stanislaw,

Thanks for your quick response. I now understand.

Thank you,
Imauny

**Comment by leonardo-lemos** [comment]
Closing it as "Won't fix".
