### ISSUE TITLE
Wingpanel overlapped with other content

### ISSUE THREAD

**Issue by KingsleyLeung03** [elementary/wingpanel#589]
### What Happened?

As the title described.  
Different windows could be placed under the top bar, causing overlapping.  
It is possible that this only happened when using HiDPI, as I'm using a 14-inch laptop with 2880*1800 resolution and HiDPI 2x.  
Let me know if you need more information.  

![image](https://github.com/user-attachments/assets/947badde-106b-47a8-bf02-f203c3d35593)

![image](https://github.com/user-attachments/assets/0f8afa31-a49c-4db8-99fe-e038667bdbba)

### Steps to Reproduce

After a fresh install of the elementary OS 8.

### Expected Behavior

The expected top bar should not cover any windows, or all windows should not be placed under the top bar.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Running under a VM, using VMware Workstation Pro 17.
CPU: Intel Core Ultra 9 185H
GPU: Intel Arc Graphics

**Comment by teamcons** [comment]
Is it this one ?
https://github.com/elementary/triage/issues/618

If yes could you thumbs up there please, so as to let know anyone reading it how much people it affects?

**Comment by KingsleyLeung03** [comment]
> Is it this one ?
> https://github.com/elementary/triage/issues/618
> 
> If yes could you thumbs up there please, so as to let know anyone reading it how much people it affects?

Thanks, I think this is the same issue.
Also, I discovered that this also happened when using Wayland.
