### ISSUE TITLE
Icons run out of room on smaller displays

### ISSUE THREAD

**Issue by suberb** [elementary/wingpanel#61]
Could you please, please, PLEASE, add one option for Wingpanel: to configure space between icons? I have a 1366 x 768 and Wingpanel's icons don't have any space to show anymore on my display.

![screenshot from 2017-11-04 18 21 41](https://user-images.githubusercontent.com/24309060/32407732-832ff164-c18d-11e7-930c-8e13369f2391.png)

**Comment by cassidyjames** [comment]
@danrabbit could we theoretically reduce the padding on smaller displays, or on "cramped" displays (certain size/number of icon combinations) by adding a class?

**Comment by danrabbit** [comment]
Yes, the padding between icons here is already set with CSS. One thing we need to do though is to remove hardcoded padding for indicators with more than one element and make sure it gets that value from CSS also.

**Comment by skewty** [comment]
Will the tray be gone / uninstallable in Juno?  Will this issue therefore stop being relevant?

**Comment by cassidyjames** [comment]
@skewty it's still theoretically an edge case to think about on certain hardware with certain stock indicators enabled. But yes, it's much less of an issue in Juno now.

**Comment by skewty** [comment]
Will `sudo apt install wingpanel-indicator-ayatana` be unofficially supported / available in Juno?

**Comment by cassidyjames** [comment]
@skewty no, see https://github.com/elementary/wingpanel/issues/96

**Comment by danirabbit** [comment]
I'm going to close this since we don't support apps injecting indicators into the panel and we also have reduced the spacing between indicators since this issue was filed
