### ISSUE TITLE
[New Feature] Make wingpanel panel opaque when something is in fullscreen mode.

### ISSUE THREAD

**Issue by Astro-City** [elementary/wingpanel#65]
Hi.  

I just thought that this would be something cool to have on Elementary.  

Imagine the following situation:  

- Since you have a dark wallpaper, the wingpanel is in transparent mode.

- Terminal is open in fullscreen.  

- You open pantheon-files in the foreground.

- The wingpanel is visible, but since is transparent you can't distinguish between what is in the wingpanel and what is in fullscreen on the background.  

If the wingpanel turned opaque when something is in fullscreen, you would be able to see the information on the wingpanel.

There is something like this on the theme css file for maximized windows.

**Comment by cassidyjames** [comment]
Fullscreen windows draw over the panel by design, so I'm not sure this makes sense.

**Comment by cassidyjames** [comment]
Let me know if you're seeing something different, but I'm going to close for now.

**Comment by Astro-City** [comment]
Hi.  

Situation:  

Workspace 1: Firefox in fullscreen

If you press super+t this will open the terminal in the foreground and suddenly you have the panel visible.

Someone suggested that if an app is in fullscreen the panel should always be hidden even if an app is in the foreground.
