### ISSUE TITLE
Use Palette API

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel#67]
We could set a dark or light color for the panel based on the wallpaper, using the upcoming Granite.Palette.

Depends on the Granite release with the new Palette API

_Moved from https://github.com/elementary/applications-menu/issues/61_

**Comment by cassidyjames** [comment]
@danrabbit mentioned we could also potentially use it for the text shadow to get a truer shadow.

**Comment by danrabbit** [comment]
After some discussion in #ux on Slack, it sounds like doing a blur-behind would end up being better than using palette for the panel background. Not sure how super worth it it would be to use for the shadows for the same reason as the panel: We'd only be able to get an average and it wouldn't really reflect what's under a certain portion of the panel. This could lead to shadows looking a lot more like glows, which I'm not sure is what we want to do
