### ISSUE TITLE
Error displaying text

### ISSUE THREAD

**Issue by alexdmz** [elementary/wingpanel#70]
Since a couple of days ago this became present on my system, all fonts/text look like this

![screenshot from 2017-11-29 20-21-59](https://user-images.githubusercontent.com/8071521/33654097-503fe720-da2c-11e7-8cd0-0e71f3e22d1a.png)
![screenshot from 2017-11-30 07-12-27](https://user-images.githubusercontent.com/8071521/33654105-532198f8-da2c-11e7-9051-2fceeba19616.png)
![screenshot from 2017-11-29 20-22-21](https://user-images.githubusercontent.com/8071521/33654109-5554ed5a-da2c-11e7-9867-8efaebd0117d.png)

**Comment by danrabbit** [comment]
Closing since this doesn't appear to be an issue with Wingpanel.

It looks like your system font has been set to the redacted font used in Screenshot Tool. You'll need to use either dconf editor or Terminal to reset the system font setting at `/org/gnome/desktop/interface/font-name`
