### ISSUE TITLE
Mouse gestures for switching pages

### ISSUE THREAD

**Issue by alex285** [elementary/wingpanel#82]
even if i use elementary a lot, every time i open the appLauncher i'm trying to switch to next/previous page by holding down mouse and pushing on right/left

is it possible to add some gestures onWingpanel appLauncher, since it feels a natural way to navigate?

![wingpanel-bug-1](https://user-images.githubusercontent.com/11244308/34920039-0c0d7d2a-f975-11e7-84a0-74c1950fda64.png)

**Comment by cassidyjames** [comment]
Right now you can sideways scroll on a trackpad, or use the mouse wheel on a normal mouse. I'm not sure what you're asking. 

Do you mean switch pages by clicking down, moving the mouse, and then releasing? If so, that's extremely inconsistent with all of GTK and elementary OS and would require weird special casing. It would also likely conflict with the existing drag-and-drop of app icons. It _should_ already work properly on a touch screen (if not, that's a separate bug), but nothing in elementary OS operates that way with a mouse cursor.

**Comment by cassidyjames** [comment]
Also, this repo is for the panel itself. For the app launcher, see https://github.com/elementary/applications-menu

**Comment by alex285** [comment]
@cassidyjames 
> Do you mean switch pages by clicking down, moving the mouse, and then releasing?

yes

> that's extremely inconsistent with all of GTK

i cant remember some GTK app doing that, however that's working on GNOME Shell appOverview (with St). i believe it is a very natural and expected behavior the way elementary application menu is made 

> Also, this repo is for the panel itself.

Sorry about that!

**Comment by cassidyjames** [comment]
This issue was moved to elementary/applications-menu#128
