### ISSUE TITLE
Mousewheel over battery icon to change brightness

### ISSUE THREAD

**Issue by orschiro** [elementary/wingpanel#85]
The same way you can change the volume using the mouse wheel over the volume icon.

Cinnamon has this feature, too, and it's quite cool!

**Comment by jeremypw** [comment]
This is already in progress - see https://github.com/elementary/wingpanel-indicator-power/pulls

**Comment by jeremypw** [comment]
Closing as this is an existing wingpanel-indicator-power issue.  Thanks for troubling to raise an issue anyway. :-)

**Comment by jeremypw** [comment]
That PR has not been merged into the master branch yet so it is not available in either the stable or unstable repositories.  To test it, you would need to compile it from source, which is at https://github.com/stsdc/wingpanel-indicator-power, and install on your system.

**Comment by orschiro** [comment]
> To test it, you would need to compile it from source, which is at https://github.com/stsdc/wingpanel-indicator-power, and install on your system.

OK, thanks for the instruction! :-)
